### 1: upload unit
POST http://localhost:3000/api/units/Fire%20Emblem%20Fates
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRpbW15MTIzIiwiaWF0IjoxNzQ5NDE2NDExLCJleHAiOjE3NDk1MDI4MTF9.wObXgeUCH79V6f0ayBmdNJ313mMwF6-6U6oEftChSFE

{
  "path": "Conquest",
  "name": "Camilla2",
  "class": "Malig Knight",
  "level": 12,
  "internalLevel": 15,
  "eternalSealCount": 0,
  "class_line": [
    [15, 1, "Malig Knight", {
      "hp": 1,
      "strength": 1,
      "magic": 10,
      "skill": 0,
      "speed": 0,
      "luck": 0,
      "defence": 0,
      "resistance": 0,
      "move": 0
    }]
  ],
  "stats": {
    "hp": 1,
    "strength": 1,
    "magic": 10,
    "skill": 0,
    "speed": 0,
    "luck": 0,
    "defence": 0,
    "resistance": 0,
    "move": 0
  },
  "equipped_skills": ["Strength +2", "Lunge"],
  "learned_skills": ["Strength +2", "Lunge"],
  "weapon_ranks": {
    "WeaponRankSwordKatana": "E",
    "WeaponRankLanceNaginata": "E",
    "WeaponRankAxeClub": "C",
    "WeaponRankTomeScroll": "D",
    "WeaponRankKnifeShuriken": "E",
    "WeaponRankBowYumi": "E",
    "WeaponRankStaffRod": "E",
    "WeaponRankStone": "E"
  },
  "weapons": ["Steel Axe", "Thunder"]
}

### 2: get units
GET http://localhost:3000/api/units/Fire%20Emblem%20Fates
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRpbW15MTIzIiwiaWF0IjoxNzQ5NDE2NDExLCJleHAiOjE3NDk1MDI4MTF9.wObXgeUCH79V6f0ayBmdNJ313mMwF6-6U6oEftChSFE

### 3: login account
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "Timmy123",
  "password": "poopooCACA"
}
### 4: register account

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "Timmy123",
  "password": "poopooCACA"
}

# export interface UniqueCharacterData {
#   name: string;
#   nickname?: string;
#   class: Class;
#   internalLevel: number;
#   level: number;
#   eternalSealCount: number;
#   class_line: [number, number, Class, StatBlock][];
#   stats: {
#     hp: number;
#     strength: number;
#     magic: number;
#     skill: number;
#     speed: number;
#     luck: number;
#     defence: number;
#     resistance: number;
#     move: number;
#   };
#   equipped_skills: Skill[];
#   learned_skills: Skill[];
#   weapon_ranks: {
#     WeaponRankSwordKatana: WeaponRank;
#     WeaponRankLanceNaginata: WeaponRank;
#     WeaponRankAxeClub: WeaponRank;
#     WeaponRankTomeScroll: WeaponRank;
#     WeaponRankKnifeShuriken: WeaponRank;
#     WeaponRankBowYumi: WeaponRank;
#     WeaponRankStaffRod: WeaponRank;
#     WeaponRankStone: WeaponRank;
#   };
#   weapons: String[];
#   selected_friendship_seal_partner: BaseCharacter | null;
#   selected_partner_seal_partner: BaseCharacter | null;
#   boon?: string;
#   bane?: string;
# }