import { Character } from "../../types/UnitStruct.tsx";
import { defaultClassData } from "./defaultClassData.tsx";
import { Class } from "../../types/ClassStruct.tsx";

const getClass = (name: string): Class => {
  const cls = defaultClassData.find((c) => c.className === name);
  if (!cls) throw new Error(`Class ${name} not found`);
  return cls;
};

export const defaultCharacters: Character[] = [
  {
    name: "Corrin (M)",
    gender: "M",
    title: "Crux of Fate",
    class: getClass("Nohr Prince"),
    baseInternalLevel: 1,
    royalty_status: true,
    level: 1,
    stats: {
      hp: 19,
      strength: 7,
      magic: 4,
      skill: 7,
      speed: 6,
      luck: 5,
      defense: 6,
      resistance: 2,
      move: 5,
    },
    base_growths: {
      hp: 45,
      strength: 45,
      magic: 30,
      skill: 40,
      speed: 45,
      luck: 45,
      defense: 35,
      resistance: 25,
    },
    personal_skill: "Supportive",
    basic_skills: {
      skill1: "Royalty",
      skill2: "N/A",
      skill3: "N/A",
      skill4: "N/A",
      skill5: "N/A",
    },
    base_class_set: {
      starting_class: getClass("Nohr Prince"),
      starting_class_tree: getClass("Nohr Prince"),
      heart_seal_classes: [],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    boon: "None selected yet",
    bane: "None selected yet",

    RouteAvailabilityBR: "Prologue",
    RouteAvailabilityCQ: "Prologue",
    RouteAvailabilityRV: "Prologue",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "D",
    },

    maxStatModifiers: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defense: 0,
      resistance: 0,
    },

    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defense: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defense: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defense: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defense: 0,
      resistance: 0,
    },

    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
  },
  {
    name: "Corrin (F)",
    gender: "F",
    title: "Crux of Fate",
    class: getClass("Nohr Princess"),
    baseInternalLevel: 1,
    royalty_status: true,
    level: 1,
    stats: {
      hp: 19,
      strength: 7,
      magic: 4,
      skill: 7,
      speed: 6,
      luck: 5,
      defense: 6,
      resistance: 2,
      move: 5,
    },
    base_growths: {
      hp: 45,
      strength: 45,
      magic: 30,
      skill: 40,
      speed: 45,
      luck: 45,
      defense: 35,
      resistance: 25,
    },
    personal_skill: "Supportive",
    basic_skills: {
      skill1: "Royalty",
      skill2: "N/A",
      skill3: "N/A",
      skill4: "N/A",
      skill5: "N/A",
    },
    base_class_set: {
      starting_class: getClass("Nohr Princess"),
      starting_class_tree: getClass("Nohr Princess"),
      heart_seal_classes: [],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    boon: "None selected yet",
    bane: "None selected yet",

    RouteAvailabilityBR: "Prologue",
    RouteAvailabilityCQ: "Prologue",
    RouteAvailabilityRV: "Prologue",

    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "D",
    },

    maxStatModifiers: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defense: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defense: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defense: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defense: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defense: 0,
      resistance: 0,
    },

    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
  },
  {
    name: "Camilla",
    gender: "F",
    title: "Bewitching Beauty",
    royalty_status: true,
    class: getClass("Malig Knight"),
    baseInternalLevel: 15,
    level: 1,
    stats: {
      hp: 30,
      strength: 19,
      magic: 11,
      skill: 15,
      speed: 19,
      luck: 12,
      defense: 18,
      resistance: 15,
      move: 8,
    },
    base_growths: {
      hp: 40,
      strength: 50,
      magic: 25,
      skill: 50,
      speed: 55,
      luck: 25,
      defense: 35,
      resistance: 45,
    },
    personal_skill: "Rose's Thorns",
    basic_skills: {
      skill1: "N/A",
      skill2: "N/A",
      skill3: "N/A",
      skill4: "N/A",
      skill5: "N/A",
    },
    base_class_set: {
      starting_class: getClass("Malig Knight"),
      starting_class_tree: getClass("Wyvern Rider"),
      heart_seal_classes: [getClass("Dark Mage")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },

    RouteAvailabilityBR: "",
    RouteAvailabilityCQ: "Chapter 10",
    RouteAvailabilityRV: "Chapter 12",

    weapon_ranks: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "C",
      WeaponRankTomeScroll: "D",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },

    maxStatModifiers: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defense: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defense: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defense: 0,
      resistance: 1,
    },
    personal_pair_up_bonuses_A: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defense: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defense: 1,
      resistance: 0,
    },

    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_B: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
  },
];








// {
//   name: "Corrin (F)",
//   gender: "F",
//   title: "Crux of Fate",
//   class: getClass("Nohr Princess"),
//   baseInternalLevel: 1,
//   royalty_status: true,
//   level: 1,
//   stats: {
//     hp: 19,
//     strength: 7,
//     magic: 4,
//     skill: 7,
//     speed: 6,
//     luck: 5,
//     defense: 6,
//     resistance: 2,
//     move: 5,
//   },
//   base_growths: {
//     hp: 45,
//     strength: 45,
//     magic: 30,
//     skill: 40,
//     speed: 45,
//     luck: 45,
//     defense: 35,
//     resistance: 25,
//   },
//   personal_skill: "Supportive",
//   basic_skills: {
//     skill1: "Royalty",
//     skill2: "N/A",
//     skill3: "N/A",
//     skill4: "N/A",
//     skill5: "N/A",
//   },
//   base_class_set: {
//     starting_class: getClass("Nohr Princess"),
//     starting_class_tree: getClass("Nohr Princess"),
//     heart_seal_classes: [],
//     friendship_seal_partners: [],
//     partner_seal_partners: [],
//     friendship_seal_base_class: null,
//     partner_seal_base_class: null,
//   },
//   boon: "None selected yet",
//   bane: "None selected yet",

//   RouteAvailabilityBR: "Prologue",
//   RouteAvailabilityCQ: "Prologue",
//   RouteAvailabilityRV: "Prologue",

//   weapon_ranks: {
//     WeaponRankSwordKatana: "E",
//     WeaponRankLanceNaginata: "n",
//     WeaponRankAxeClub: "n",
//     WeaponRankTomeScroll: "n",
//     WeaponRankKnifeShuriken: "n",
//     WeaponRankBowYumi: "n",
//     WeaponRankStaffRod: "n",
//     WeaponRankStone: "D",
//   },

//   maxStatModifiers: {
//     strength: 0,
//     magic: 0,
//     skill: 0,
//     speed: 0,
//     luck: 0,
//     defense: 0,
//     resistance: 0,
//   },
//   personal_pair_up_bonuses_base: {
//     dodge: 5,
//   },
//   personal_pair_up_bonuses_C: {
//     strength: 0,
//     magic: 0,
//     skill: 0,
//     speed: 0,
//     luck: 0,
//     defense: 0,
//     resistance: 0,
//   },
//   personal_pair_up_bonuses_B: {
//     strength: 0,
//     magic: 0,
//     skill: 0,
//     speed: 0,
//     luck: 0,
//     defense: 0,
//     resistance: 0,
//   },
//   personal_pair_up_bonuses_A: {
//     strength: 0,
//     magic: 0,
//     skill: 0,
//     speed: 0,
//     luck: 0,
//     defense: 0,
//     resistance: 0,
//   },
//   personal_pair_up_bonuses_S: {
//     strength: 0,
//     magic: 0,
//     skill: 0,
//     speed: 0,
//     luck: 0,
//     defense: 0,
//     resistance: 0,
//   },

//   support_bonus_base: {
//     Crit: 0,
//     CritAvoid: 0,
//     Hit: 10,
//     Avoid: 0,
//   },
//   support_bonus_C: {
//     Crit: 0,
//     CritAvoid: 0,
//     Hit: 0,
//     Avoid: 0,
//   },
//   support_bonus_B: {
//     Crit: 0,
//     CritAvoid: 0,
//     Hit: 0,
//     Avoid: 0,
//   },
//   support_bonus_A: {
//     Crit: 0,
//     CritAvoid: 0,
//     Hit: 0,
//     Avoid: 0,
//   },
//   support_bonus_S: {
//     Crit: 0,
//     CritAvoid: 0,
//     Hit: 0,
//     Avoid: 0,
//   },
// },