import { Class } from "../../types/Fire Emblem Fates/ClassStruct.tsx";
import { getSkill } from "./defaultSkills.tsx";
export const defaultClassData: Class[] = [
  {
    className: "Nohr Prince",
    classTree: [], //Init empty and populate later so no crashes
    promotionStatus: false,
    description:
      "A Nohrian royal fitted with their kingdom's equipment. Their body conceals the power of dragons.",
    TypeProperty: ["Dragon"],
    classBaseStats: {
      hp: 17,
      strength: 7,
      magic: 3,
      skill: 4,
      speed: 5,
      luck: 2,
      defence: 5,
      resistance: 2,
      move: 5,

      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 15,
      strength: 15,
      magic: 10,
      skill: 10,
      speed: 10,
      luck: 10,
      defence: 10,
      resistance: 5,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "B",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "B",
    },
    MaxStatCaps: {
      hp: 40,
      strength: 23,
      magic: 17,
      skill: 19,
      speed: 21,
      luck: 22,
      defence: 21,
      resistance: 19,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 0,
      skill: 1,
      speed: 1,
      luck: 2,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Nohr Princess",
    classTree: [],
    promotionStatus: false,
    description:
      "A Nohrian royal fitted with their kingdom's equipment. Their body conceals the power of dragons.",
    TypeProperty: ["Dragon"],
    classBaseStats: {
      hp: 17,
      strength: 7,
      magic: 3,
      skill: 4,
      speed: 5,
      luck: 2,
      defence: 5,
      resistance: 2,
      move: 5,

      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 15,
      strength: 15,
      magic: 10,
      skill: 10,
      speed: 10,
      luck: 10,
      defence: 10,
      resistance: 5,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "B",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "B",
    },
    MaxStatCaps: {
      hp: 40,
      strength: 23,
      magic: 17,
      skill: 19,
      speed: 21,
      luck: 22,
      defence: 21,
      resistance: 19,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 0,
      skill: 1,
      speed: 1,
      luck: 2,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Hoshido Noble",
    classTree: [],
    promotionStatus: true,
    description:
      "Royals whose heart aligns with Hoshido. Wields rods in addition to katanas and dragonstones.",
    TypeProperty: ["Dragon"],
    classBaseStats: {
      hp: 19,
      strength: 10,
      magic: 4,
      skill: 5,
      speed: 6,
      luck: 4,
      defence: 7,
      resistance: 3,
      move: 6,

      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 15,
      strength: 15,
      magic: 10,
      skill: 10,
      speed: 10,
      luck: 10,
      defence: 15,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "A",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "B",
      WeaponRankStone: "A",
    },
    MaxStatCaps: {
      hp: 60,
      strength: 34,
      magic: 28,
      skill: 29,
      speed: 30,
      luck: 33,
      defence: 31,
      resistance: 28,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 0,
      skill: 1,
      speed: 1,
      luck: 2,
      defence: 2,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Nohr Noble",
    classTree: [],
    promotionStatus: true,
    description:
      "Royals whose heart aligns with Nohr. Wields magic in addition to swords and dragonstones.",
    TypeProperty: ["Dragon"],
    classBaseStats: {
      hp: 18,
      strength: 8,
      magic: 6,
      skill: 4,
      speed: 7,
      luck: 2,
      defence: 6,
      resistance: 6,
      move: 6,

      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 15,
      strength: 10,
      magic: 15,
      skill: 5,
      speed: 15,
      luck: 5,
      defence: 5,
      resistance: 15,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "A",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "B",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "A",
    },
    MaxStatCaps: {
      hp: 60,
      strength: 32,
      magic: 31,
      skill: 28,
      speed: 32,
      luck: 27,
      defence: 29,
      resistance: 32,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 2,
      skill: 1,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 2,
      move: 0,
    },
  },
  {
    className: "Samurai",
    classTree: [],
    promotionStatus: false,
    description:
      "Those who follow the path of the katana. Excels in battle by taking advantage of its speed.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 17,
      strength: 4,
      magic: 0,
      skill: 5,
      speed: 8,
      luck: 3,
      defence: 3,
      resistance: 3,
      move: 5,

      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 10,
      magic: 0,
      skill: 15,
      speed: 20,
      luck: 15,
      defence: 0,
      resistance: 10,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "B",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 40,
      strength: 20,
      magic: 16,
      skill: 23,
      speed: 25,
      luck: 24,
      defence: 18,
      resistance: 20,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 4,
      luck: 2,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Swordmaster",
    classTree: [],
    promotionStatus: true,
    description:
      "Those who have reached the pinnacle of the katana. Has exceptional speed and evasion.",
    TypeProperty: [],
    classBaseStats: {
      hp: 18,
      strength: 6,
      magic: 2,
      skill: 7,
      speed: 11,
      luck: 4,
      defence: 5,
      resistance: 5,
      move: 6,

      BonusCrit: 10,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 10,
    },
    classGrowths: {
      hp: 10,
      strength: 10,
      magic: 5,
      skill: 15,
      speed: 20,
      luck: 15,
      defence: 0,
      resistance: 10,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "S",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 55,
      strength: 30,
      magic: 28,
      skill: 32,
      speed: 35,
      luck: 33,
      defence: 27,
      resistance: 31,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 5,
      luck: 3,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Master of Arms",
    classTree: [],
    promotionStatus: true,
    description:
      "Those who can handle any type of enemy. Adept with katanas, naginatas and clubs.",
    TypeProperty: [],
    classBaseStats: {
      hp: 20,
      strength: 8,
      magic: 0,
      skill: 6,
      speed: 9,
      luck: 3,
      defence: 7,
      resistance: 3,
      move: 6,

      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 20,
      strength: 15,
      magic: 0,
      skill: 10,
      speed: 10,
      luck: 10,
      defence: 10,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "A",
      WeaponRankLanceNaginata: "B",
      WeaponRankAxeClub: "B",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 65,
      strength: 33,
      magic: 25,
      skill: 30,
      speed: 30,
      luck: 31,
      defence: 31,
      resistance: 28,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 0,
      skill: 2,
      speed: 2,
      luck: 0,
      defence: 2,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Oni Savage",
    classTree: [],
    promotionStatus: false,
    description:
      "A demon-like warrior who wields clubs. Boasts high offence and defence.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 18,
      strength: 6,
      magic: 1,
      skill: 2,
      speed: 5,
      luck: 0,
      defence: 7,
      resistance: 1,
      move: 5,

      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 20,
      strength: 20,
      magic: 10,
      skill: 0,
      speed: 10,
      luck: 0,
      defence: 20,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "B",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 45,
      strength: 24,
      magic: 19,
      skill: 16,
      speed: 20,
      luck: 17,
      defence: 23,
      resistance: 18,
    },
    classPairUpBonuses: {
      strength: 4,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 2,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Oni Chieftain",
    classTree: [],
    promotionStatus: true,
    description:
      "Those who have transcended to become a demon-god. They pulverise enemies with their clubs and spells.",
    TypeProperty: [],
    classBaseStats: {
      hp: 19,
      strength: 9,
      magic: 5,
      skill: 2,
      speed: 7,
      luck: 0,
      defence: 10,
      resistance: 5,
      move: 6,

      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 20,
      magic: 15,
      skill: 0,
      speed: 10,
      luck: 0,
      defence: 20,
      resistance: 5,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "A",
      WeaponRankTomeScroll: "B",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 60,
      strength: 34,
      magic: 28,
      skill: 25,
      speed: 30,
      luck: 25,
      defence: 36,
      resistance: 31,
    },
    classPairUpBonuses: {
      strength: 4,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 4,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Blacksmith",
    classTree: [],
    promotionStatus: true,
    description:
      "Artisans who craft weapons. Wields katanas and clubs and boasts superior skill.",
    TypeProperty: [],
    classBaseStats: {
      hp: 21,
      strength: 8,
      magic: 0,
      skill: 9,
      speed: 8,
      luck: 3,
      defence: 8,
      resistance: 2,
      move: 6,

      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 20,
      strength: 15,
      magic: 0,
      skill: 15,
      speed: 10,
      luck: 5,
      defence: 15,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "B",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "A",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 65,
      strength: 33,
      magic: 25,
      skill: 32,
      speed: 31,
      luck: 30,
      defence: 32,
      resistance: 27,
    },
    classPairUpBonuses: {
      strength: 3,
      magic: 0,
      skill: 2,
      speed: 0,
      luck: 0,
      defence: 3,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Spear Fighter",
    classTree: [],
    promotionStatus: false,
    description:
      "Those who follow the path of the naginata. Excels in battle by dropping the enemy’s defence.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 17,
      strength: 6,
      magic: 0,
      skill: 6,
      speed: 6,
      luck: 2,
      defence: 5,
      resistance: 2,
      move: 5,

      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 15,
      strength: 15,
      magic: 0,
      skill: 15,
      speed: 15,
      luck: 5,
      defence: 10,
      resistance: 5,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "B",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 40,
      strength: 22,
      magic: 15,
      skill: 23,
      speed: 22,
      luck: 21,
      defence: 22,
      resistance: 21,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 0,
      skill: 2,
      speed: 2,
      luck: 0,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Spear Master",
    classTree: [],
    promotionStatus: true,
    description:
      "Those who have reached the pinnacle of the naginata. Has stable abilities.",
    TypeProperty: [],
    classBaseStats: {
      hp: 18,
      strength: 9,
      magic: 0,
      skill: 8,
      speed: 8,
      luck: 3,
      defence: 7,
      resistance: 3,
      move: 6,

      BonusCrit: 10,
      BonusCritAvoid: 10,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 15,
      strength: 15,
      magic: 0,
      skill: 15,
      speed: 15,
      luck: 5,
      defence: 10,
      resistance: 50,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "S",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 60,
      strength: 34,
      magic: 25,
      skill: 33,
      speed: 32,
      luck: 29,
      defence: 30,
      resistance: 29,
    },
    classPairUpBonuses: {
      strength: 3,
      magic: 0,
      skill: 3,
      speed: 2,
      luck: 0,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Basara",
    classTree: [],
    promotionStatus: true,
    description:
      "Those who prefer a quirky and free-spirited life. Disrupts enemies with their naginatas and scrolls.",
    TypeProperty: [],
    classBaseStats: {
      hp: 20,
      strength: 7,
      magic: 5,
      skill: 7,
      speed: 7,
      luck: 5,
      defence: 7,
      resistance: 6,
      move: 6,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 20,
      strength: 10,
      magic: 10,
      skill: 10,
      speed: 10,
      luck: 15,
      defence: 5,
      resistance: 10,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "A",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "B",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 65,
      strength: 31,
      magic: 30,
      skill: 30,
      speed: 31,
      luck: 35,
      defence: 30,
      resistance: 32,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 5,
      defence: 0,
      resistance: 3,
      move: 0,
    },
  },
  {
    className: "Diviner",
    classTree: [],
    promotionStatus: false,
    description:
      "Those who study the art of spell-casting. They fight using Hoshidan scrolls.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 15,
      strength: 0,
      magic: 4,
      skill: 5,
      speed: 6,
      luck: 1,
      defence: 1,
      resistance: 3,
      move: 5,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 5,
      magic: 15,
      skill: 10,
      speed: 15,
      luck: 5,
      defence: 0,
      resistance: 10,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "B",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 35,
      strength: 17,
      magic: 22,
      skill: 20,
      speed: 23,
      luck: 19,
      defence: 16,
      resistance: 20,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 3,
      skill: 0,
      speed: 3,
      luck: 0,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Onmyoji",
    classTree: [],
    promotionStatus: true,
    description:
      "Those who have learned myriad spells. Well-versed with both scrolls and rods.",
    TypeProperty: [],
    classBaseStats: {
      hp: 16,
      strength: 0,
      magic: 7,
      skill: 6,
      speed: 7,
      luck: 2,
      defence: 3,
      resistance: 6,
      move: 6,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 0,
      magic: 20,
      skill: 10,
      speed: 15,
      luck: 0,
      defence: 0,
      resistance: 15,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "A",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "B",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 45,
      strength: 25,
      magic: 33,
      skill: 31,
      speed: 32,
      luck: 27,
      defence: 25,
      resistance: 31,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 4,
      skill: 0,
      speed: 4,
      luck: 0,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Monk",
    classTree: [],
    promotionStatus: false,
    description:
      "Men who study to attain enlightenment. They can heal allies with rods.",
    TypeProperty: [],
    classBaseStats: {
      hp: 16,
      strength: 0,
      magic: 3,
      skill: 5,
      speed: 5,
      luck: 4,
      defence: 2,
      resistance: 5,
      move: 5,
      BonusCrit: 0,
      BonusCritAvoid: 10,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 5,
      magic: 10,
      skill: 10,
      speed: 15,
      luck: 15,
      defence: 0,
      resistance: 20,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "B",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 35,
      strength: 18,
      magic: 21,
      skill: 20,
      speed: 22,
      luck: 23,
      defence: 17,
      resistance: 24,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 2,
      skill: 0,
      speed: 0,
      luck: 2,
      defence: 0,
      resistance: 2,
      move: 0,
    },
  },
  {
    className: "Shrine Maiden",
    classTree: [],
    promotionStatus: false,
    description:
      "Maidens dedicated to serving the gods. They can heal allies with rods.",
    TypeProperty: [],
    classBaseStats: {
      hp: 16,
      strength: 0,
      magic: 3,
      skill: 5,
      speed: 5,
      luck: 4,
      defence: 2,
      resistance: 5,
      move: 5,
      BonusCrit: 0,
      BonusCritAvoid: 10,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 5,
      magic: 10,
      skill: 10,
      speed: 15,
      luck: 15,
      defence: 0,
      resistance: 20,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "B",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 35,
      strength: 18,
      magic: 21,
      skill: 20,
      speed: 22,
      luck: 23,
      defence: 17,
      resistance: 24,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 2,
      skill: 0,
      speed: 0,
      luck: 2,
      defence: 0,
      resistance: 2,
      move: 0,
    },
  },
  {
    className: "Great Master",
    classTree: [],
    promotionStatus: true,
    description:
      "Men who have journeyed to enlightenment. They heal with rods and vanquish foes with naginatas.",
    TypeProperty: [],
    classBaseStats: {
      hp: 19,
      strength: 8,
      magic: 6,
      skill: 6,
      speed: 8,
      luck: 5,
      defence: 6,
      resistance: 7,
      move: 6,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 15,
      magic: 5,
      skill: 5,
      speed: 15,
      luck: 15,
      defence: 10,
      resistance: 10,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "B",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "A",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 55,
      strength: 32,
      magic: 30,
      skill: 31,
      speed: 33,
      luck: 32,
      defence: 28,
      resistance: 32,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 3,
      skill: 0,
      speed: 0,
      luck: 2,
      defence: 0,
      resistance: 3,
      move: 0,
    },
  },
  {
    className: "Priestess",
    classTree: [],
    promotionStatus: true,
    description:
      "Maidens who fight for the gods and the people. They heal with rods and vanquish foes with yumi.",
    TypeProperty: [],
    classBaseStats: {
      hp: 19,
      strength: 6,
      magic: 7,
      skill: 6,
      speed: 9,
      luck: 5,
      defence: 5,
      resistance: 8,
      move: 6,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 10,
      magic: 10,
      skill: 5,
      speed: 15,
      luck: 15,
      defence: 0,
      resistance: 20,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "B",
      WeaponRankStaffRod: "A",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 50,
      strength: 29,
      magic: 32,
      skill: 30,
      speed: 33,
      luck: 34,
      defence: 26,
      resistance: 34,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 3,
      skill: 0,
      speed: 0,
      luck: 2,
      defence: 0,
      resistance: 3,
      move: 0,
    },
  },
  {
    className: "Sky Knight",
    classTree: [],
    promotionStatus: false,
    description:
      "Warriors who soar the skies astride a pegasus. Has excellent speed and resistance.",
    TypeProperty: ["Beast", "Flying"],
    parallelClass: null,
    classBaseStats: {
      hp: 16,
      strength: 3,
      magic: 0,
      skill: 5,
      speed: 7,
      luck: 4,
      defence: 2,
      resistance: 6,
      move: 7,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 10,
      magic: 0,
      skill: 10,
      speed: 15,
      luck: 20,
      defence: 0,
      resistance: 20,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "B",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 35,
      strength: 19,
      magic: 16,
      skill: 21,
      speed: 23,
      luck: 25,
      defence: 18,
      resistance: 25,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 3,
      luck: 0,
      defence: 0,
      resistance: 3,
      move: 0,
    },
  },
  {
    className: "Falcon Knight",
    classTree: [],
    promotionStatus: true,
    description:
      "High-ranking Sky Knights. In addition to naginatas, they can guard allies with rods.",
    TypeProperty: ["Beast", "Flying"],
    classBaseStats: {
      hp: 18,
      strength: 5,
      magic: 4,
      skill: 6,
      speed: 10,
      luck: 5,
      defence: 5,
      resistance: 9,
      move: 8,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 10,
      magic: 10,
      skill: 10,
      speed: 15,
      luck: 20,
      defence: 0,
      resistance: 20,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "A",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "B",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 55,
      strength: 28,
      magic: 27,
      skill: 30,
      speed: 34,
      luck: 35,
      defence: 27,
      resistance: 35,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 3,
      luck: 0,
      defence: 0,
      resistance: 3,
      move: 1,
    },
  },
  {
    className: "Kinshi Knight",
    classTree: [],
    promotionStatus: true,
    description:
      "Those who fight astride the fabled golden kite. With their naginatas and yumi, they dominate the skies.",
    TypeProperty: ["Beast", "Flying"],
    classBaseStats: {
      hp: 17,
      strength: 4,
      magic: 1,
      skill: 9,
      speed: 8,
      luck: 5,
      defence: 4,
      resistance: 7,
      move: 8,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 5,
      magic: 0,
      skill: 15,
      speed: 15,
      luck: 15,
      defence: 0,
      resistance: 15,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "B",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "A",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 50,
      strength: 27,
      magic: 26,
      skill: 33,
      speed: 31,
      luck: 34,
      defence: 25,
      resistance: 31,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 2,
      speed: 2,
      luck: 2,
      defence: 0,
      resistance: 0,
      move: 1,
    },
  },
  {
    className: "Archer",
    classTree: [],
    promotionStatus: false,
    description: "Those who follow the path of the yumi. Has superior skill.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 17,
      strength: 5,
      magic: 0,
      skill: 7,
      speed: 5,
      luck: 2,
      defence: 4,
      resistance: 1,
      move: 5,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 15,
      magic: 0,
      skill: 15,
      speed: 15,
      luck: 5,
      defence: 10,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "B",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 40,
      strength: 21,
      magic: 15,
      skill: 23,
      speed: 21,
      luck: 20,
      defence: 20,
      resistance: 17,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 0,
      skill: 2,
      speed: 2,
      luck: 0,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Sniper",
    classTree: [],
    promotionStatus: true,
    description:
      "Those who have reached the pinnacle of the yumi. Has exceptional accuracy and critical rate.",
    TypeProperty: [],
    classBaseStats: {
      hp: 19,
      strength: 7,
      magic: 0,
      skill: 10,
      speed: 9,
      luck: 3,
      defence: 6,
      resistance: 2,
      move: 6,
      BonusCrit: 10,
      BonusCritAvoid: 0,
      BonusHit: 10,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 15,
      magic: 0,
      skill: 20,
      speed: 15,
      luck: 5,
      defence: 10,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "S",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 55,
      strength: 31,
      magic: 25,
      skill: 35,
      speed: 33,
      luck: 30,
      defence: 31,
      resistance: 28,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 0,
      skill: 3,
      speed: 3,
      luck: 0,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Ninja",
    classTree: [],
    promotionStatus: false,
    description:
      "Those who freely operate in the shadows. They use shurikens to attack and weaken enemies.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 16,
      strength: 3,
      magic: 0,
      skill: 8,
      speed: 8,
      luck: 1,
      defence: 3,
      resistance: 3,
      move: 5,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 5,
      strength: 5,
      magic: 0,
      skill: 20,
      speed: 20,
      luck: 0,
      defence: 5,
      resistance: 15,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "B",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 35,
      strength: 17,
      magic: 15,
      skill: 25,
      speed: 25,
      luck: 18,
      defence: 19,
      resistance: 20,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 3,
      luck: 0,
      defence: 0,
      resistance: 0,
      move: 1,
    },
  },
  {
    className: "Master Ninja",
    classTree: [],
    promotionStatus: true,
    description:
      "Ninja leaders. They execute targets with their shurikens and katanas.",
    TypeProperty: [],
    classBaseStats: {
      hp: 17,
      strength: 5,
      magic: 0,
      skill: 10,
      speed: 11,
      luck: 2,
      defence: 4,
      resistance: 8,
      move: 6,
      BonusCrit: 5,
      BonusCritAvoid: 5,
      BonusHit: 5,
      BonusAvoid: 5,
    },
    classGrowths: {
      hp: 5,
      strength: 5,
      magic: 0,
      skill: 20,
      speed: 20,
      luck: 0,
      defence: 5,
      resistance: 20,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "B",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "S",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 55,
      strength: 27,
      magic: 25,
      skill: 35,
      speed: 35,
      luck: 28,
      defence: 26,
      resistance: 34,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 2,
      speed: 4,
      luck: 0,
      defence: 0,
      resistance: 0,
      move: 1,
    },
  },
  {
    className: "Mechanist",
    classTree: [],
    promotionStatus: true,
    description:
      "Artisans who craft puppets. They wield shurikens and yumi with great dexterity.",
    TypeProperty: ["Automaton"],
    classBaseStats: {
      hp: 18,
      strength: 7,
      magic: 0,
      skill: 9,
      speed: 7,
      luck: 2,
      defence: 6,
      resistance: 6,
      move: 7,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 10,
      magic: 0,
      skill: 15,
      speed: 10,
      luck: 5,
      defence: 5,
      resistance: 15,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "A",
      WeaponRankBowYumi: "B",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 60,
      strength: 30,
      magic: 25,
      skill: 33,
      speed: 30,
      luck: 30,
      defence: 31,
      resistance: 31,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 0,
      skill: 2,
      speed: 0,
      luck: 0,
      defence: 2,
      resistance: 2,
      move: 0,
    },
  },
  {
    className: "Apothecary",
    classTree: [],
    promotionStatus: false,
    description:
      "Herb-sellers with extensive knowledge of herbs. They protect themselves with yumi.",
    TypeProperty: [],
    classBaseStats: {
      hp: 18,
      strength: 6,
      magic: 0,
      skill: 4,
      speed: 4,
      luck: 2,
      defence: 6,
      resistance: 2,
      move: 5,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 20,
      strength: 20,
      magic: 0,
      skill: 10,
      speed: 10,
      luck: 5,
      defence: 10,
      resistance: 5,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "B",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 45,
      strength: 24,
      magic: 15,
      skill: 19,
      speed: 19,
      luck: 21,
      defence: 23,
      resistance: 20,
    },
    classPairUpBonuses: {
      strength: 3,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 2,
      resistance: 1,
      move: 0,
    },
  },
  {
    className: "Merchant",
    classTree: [],
    promotionStatus: true,
    description:
      "Merchants with excellent business acumen. They protect their fortune with naginatas and yumi.",
    TypeProperty: [],
    classBaseStats: {
      hp: 20,
      strength: 8,
      magic: 0,
      skill: 6,
      speed: 5,
      luck: 4,
      defence: 8,
      resistance: 5,
      move: 6,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 20,
      strength: 20,
      magic: 0,
      skill: 10,
      speed: 5,
      luck: 15,
      defence: 10,
      resistance: 5,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "B",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "A",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 65,
      strength: 33,
      magic: 25,
      skill: 29,
      speed: 28,
      luck: 32,
      defence: 33,
      resistance: 30,
    },
    classPairUpBonuses: {
      strength: 3,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 3,
      resistance: 2,
      move: 0,
    },
  },
  {
    className: "Kitsune",
    classTree: [],
    promotionStatus: false,
    description:
      "A long-living fox who bewitches humans. Boasts high speed and resistance.",
    TypeProperty: ["Beast"],
    parallelClass: null,
    classBaseStats: {
      hp: 16,
      strength: 5,
      magic: 1,
      skill: 6,
      speed: 8,
      luck: 4,
      defence: 1,
      resistance: 4,
      move: 5,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 10,
      magic: 0,
      skill: 15,
      speed: 20,
      luck: 10,
      defence: 0,
      resistance: 20,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "B",
    },
    MaxStatCaps: {
      hp: 40,
      strength: 20,
      magic: 18,
      skill: 23,
      speed: 24,
      luck: 24,
      defence: 18,
      resistance: 23,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 4,
      luck: 2,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Nine-Tails",
    classTree: [],
    promotionStatus: true,
    description:
      "A high-ranking fox with great spiritual power. Has better abilities than a Kitsune.",
    TypeProperty: ["Beast"],
    classBaseStats: {
      hp: 19,
      strength: 6,
      magic: 2,
      skill: 9,
      speed: 10,
      luck: 5,
      defence: 2,
      resistance: 8,
      move: 6,
      BonusCrit: 5,
      BonusCritAvoid: 10,
      BonusHit: 0,
      BonusAvoid: 10,
    },
    classGrowths: {
      hp: 10,
      strength: 10,
      magic: 0,
      skill: 15,
      speed: 20,
      luck: 10,
      defence: 0,
      resistance: 20,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "S",
    },
    MaxStatCaps: {
      hp: 55,
      strength: 29,
      magic: 29,
      skill: 33,
      speed: 34,
      luck: 33,
      defence: 27,
      resistance: 34,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 5,
      luck: 3,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Songstress",
    classTree: [],
    promotionStatus: null,
    description:
      "A female who calms minds with her beautiful songs. Can sing to allow allies another action.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 16,
      strength: 3,
      magic: 0,
      skill: 6,
      speed: 5,
      luck: 3,
      defence: 2,
      resistance: 3,
      move: 5,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 10,
      magic: 0,
      skill: 20,
      speed: 20,
      luck: 20,
      defence: 0,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "C",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 45,
      strength: 28,
      magic: 27,
      skill: 31,
      speed: 31,
      luck: 35,
      defence: 27,
      resistance: 28,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 2,
      speed: 2,
      luck: 4,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Villager",
    classTree: [],
    promotionStatus: false,
    description:
      "Common folk who live in villages. During battles, they fight wielding naginatas.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 17,
      strength: 5,
      magic: 0,
      skill: 4,
      speed: 5,
      luck: 3,
      defence: 4,
      resistance: 0,
      move: 5,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 10,
      magic: 0,
      skill: 10,
      speed: 10,
      luck: 20,
      defence: 10,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "C",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 35,
      strength: 19,
      magic: 15,
      skill: 19,
      speed: 19,
      luck: 22,
      defence: 18,
      resistance: 15,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 3,
      speed: 0,
      luck: 3,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Cavalier",
    classTree: [],
    promotionStatus: false,
    description:
      "Knights who fight on horseback. Can use both swords and lances.",
    TypeProperty: ["Beast"],
    parallelClass: null,
    classBaseStats: {
      hp: 17,
      strength: 6,
      magic: 0,
      skill: 5,
      speed: 5,
      luck: 3,
      defence: 5,
      resistance: 3,
      move: 7,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 15,
      magic: 0,
      skill: 10,
      speed: 10,
      luck: 15,
      defence: 10,
      resistance: 5,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "B",
      WeaponRankLanceNaginata: "B",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 40,
      strength: 22,
      magic: 15,
      skill: 21,
      speed: 20,
      luck: 24,
      defence: 22,
      resistance: 21,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 2,
      resistance: 2,
      move: 0,
    },
  },
  {
    className: "Paladin",
    classTree: [],
    promotionStatus: true,
    description:
      "High-ranking knights praised for their bravery. They have better capabilities than a Cavalier.",
    TypeProperty: ["Beast"],
    classBaseStats: {
      hp: 19,
      strength: 8,
      magic: 1,
      skill: 7,
      speed: 7,
      luck: 4,
      defence: 7,
      resistance: 6,
      move: 8,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 15,
      magic: 0,
      skill: 10,
      speed: 10,
      luck: 15,
      defence: 10,
      resistance: 10,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "A",
      WeaponRankLanceNaginata: "A",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 60,
      strength: 31,
      magic: 26,
      skill: 30,
      speed: 30,
      luck: 32,
      defence: 32,
      resistance: 32,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 2,
      resistance: 2,
      move: 1,
    },
  },
  {
    className: "Great Knight",
    classTree: [],
    promotionStatus: true,
    description:
      "Armoured riders. Capable of wielding swords, lances and axes.",
    TypeProperty: ["Armor", "Beast"],
    classBaseStats: {
      hp: 21,
      strength: 10,
      magic: 0,
      skill: 6,
      speed: 6,
      luck: 3,
      defence: 10,
      resistance: 2,
      move: 7,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 20,
      strength: 20,
      magic: 0,
      skill: 10,
      speed: 5,
      luck: 5,
      defence: 20,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "B",
      WeaponRankLanceNaginata: "A",
      WeaponRankAxeClub: "B",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 65,
      strength: 35,
      magic: 25,
      skill: 29,
      speed: 27,
      luck: 28,
      defence: 37,
      resistance: 28,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 4,
      resistance: 1,
      move: 0,
    },
  },
  {
    className: "Knight",
    classTree: [],
    promotionStatus: false,
    description:
      "Foot-soldiers encased in heavy armour. Slow but has high defence.",
    TypeProperty: ["Armor"],
    parallelClass: null,
    classBaseStats: {
      hp: 19,
      strength: 8,
      magic: 0,
      skill: 5,
      speed: 3,
      luck: 3,
      defence: 8,
      resistance: 1,
      move: 4,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 20,
      strength: 20,
      magic: 0,
      skill: 15,
      speed: 5,
      luck: 10,
      defence: 20,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "B",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 45,
      strength: 24,
      magic: 15,
      skill: 22,
      speed: 17,
      luck: 22,
      defence: 26,
      resistance: 18,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 4,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "General",
    classTree: [],
    promotionStatus: true,
    description:
      "Generals fortified from head to foot with heavy armour. They possess exceptional defence.",
    TypeProperty: ["Armor"],
    classBaseStats: {
      hp: 22,
      strength: 11,
      magic: 0,
      skill: 7,
      speed: 3,
      luck: 4,
      defence: 12,
      resistance: 3,
      move: 5,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 25,
      strength: 20,
      magic: 0,
      skill: 15,
      speed: 0,
      luck: 10,
      defence: 20,
      resistance: 5,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "A",
      WeaponRankAxeClub: "B",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 70,
      strength: 38,
      magic: 25,
      skill: 32,
      speed: 25,
      luck: 32,
      defence: 40,
      resistance: 30,
    },
    classPairUpBonuses: {
      strength: 3,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 5,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Fighter",
    classTree: [],
    promotionStatus: false,
    description:
      "Axe-fighters with a superior body. Has high attack power, but weak defences.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 19,
      strength: 7,
      magic: 0,
      skill: 6,
      speed: 6,
      luck: 2,
      defence: 4,
      resistance: 1,
      move: 5,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 20,
      strength: 20,
      magic: 0,
      skill: 15,
      speed: 15,
      luck: 5,
      defence: 5,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "B",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 45,
      strength: 25,
      magic: 15,
      skill: 23,
      speed: 22,
      luck: 21,
      defence: 19,
      resistance: 18,
    },
    classPairUpBonuses: {
      strength: 4,
      magic: 0,
      skill: 0,
      speed: 2,
      luck: 0,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Berserker",
    classTree: [],
    promotionStatus: true,
    description:
      "Crazed fighters who fight with axes. They excel in performing critical hits.",
    TypeProperty: [],
    classBaseStats: {
      hp: 24,
      strength: 12,
      magic: 0,
      skill: 8,
      speed: 9,
      luck: 0,
      defence: 5,
      resistance: 0,
      move: 6,
      BonusCrit: 20,
      BonusCritAvoid: -5,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 30,
      strength: 25,
      magic: 0,
      skill: 15,
      speed: 15,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "S",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 70,
      strength: 40,
      magic: 25,
      skill: 32,
      speed: 33,
      luck: 25,
      defence: 27,
      resistance: 25,
    },
    classPairUpBonuses: {
      strength: 5,
      magic: 0,
      skill: 0,
      speed: 3,
      luck: 0,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Mercenary",
    classTree: [],
    promotionStatus: false,
    description:
      "Sell-swords who can handle any mission. They have well-balanced abilities and superior skill.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 17,
      strength: 5,
      magic: 0,
      skill: 7,
      speed: 6,
      luck: 2,
      defence: 5,
      resistance: 2,
      move: 5,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 15,
      magic: 0,
      skill: 20,
      speed: 15,
      luck: 5,
      defence: 10,
      resistance: 5,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "B",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 40,
      strength: 22,
      magic: 15,
      skill: 24,
      speed: 22,
      luck: 20,
      defence: 21,
      resistance: 19,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 2,
      speed: 3,
      luck: 0,
      defence: 1,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Hero",
    classTree: [],
    promotionStatus: true,
    description:
      "Heroes renowned for their bravery. They wield swords and axes and can adapt to any battlefield.",
    TypeProperty: [],
    classBaseStats: {
      hp: 20,
      strength: 8,
      magic: 0,
      skill: 10,
      speed: 8,
      luck: 3,
      defence: 7,
      resistance: 2,
      move: 6,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 20,
      strength: 15,
      magic: 0,
      skill: 20,
      speed: 15,
      luck: 5,
      defence: 10,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "A",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "B",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 60,
      strength: 32,
      magic: 25,
      skill: 35,
      speed: 32,
      luck: 31,
      defence: 30,
      resistance: 27,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 3,
      speed: 3,
      luck: 0,
      defence: 2,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Bow Knight",
    classTree: [],
    promotionStatus: true,
    description:
      "Knights who rain arrows from horseback. In addition to bows, they can wield swords.",
    TypeProperty: ["Beast"],
    classBaseStats: {
      hp: 18,
      strength: 6,
      magic: 0,
      skill: 8,
      speed: 9,
      luck: 3,
      defence: 5,
      resistance: 6,
      move: 8,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 10,
      magic: 0,
      skill: 15,
      speed: 15,
      luck: 10,
      defence: 0,
      resistance: 10,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "B",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "A",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 55,
      strength: 29,
      magic: 25,
      skill: 32,
      speed: 33,
      luck: 30,
      defence: 27,
      resistance: 32,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 3,
      speed: 3,
      luck: 0,
      defence: 0,
      resistance: 0,
      move: 1,
    },
  },
  {
    className: "Outlaw",
    classTree: [],
    promotionStatus: false,
    description:
      "Crooks who are skilled at picking locks. Wield bows and boast high speed and resistance.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 16,
      strength: 3,
      magic: 1,
      skill: 4,
      speed: 8,
      luck: 1,
      defence: 2,
      resistance: 4,
      move: 5,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 10,
      magic: 5,
      skill: 10,
      speed: 20,
      luck: 0,
      defence: 0,
      resistance: 20,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "B",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 35,
      strength: 19,
      magic: 18,
      skill: 20,
      speed: 24,
      luck: 18,
      defence: 17,
      resistance: 22,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 2,
      luck: 0,
      defence: 0,
      resistance: 2,
      move: 1,
    },
  },
  {
    className: "Adventurer",
    classTree: [],
    promotionStatus: true,
    description:
      "Glory-seekers who investigate ruins for treasure. With their bows and staves, they're capable of many things.",
    TypeProperty: [],
    classBaseStats: {
      hp: 17,
      strength: 4,
      magic: 6,
      skill: 6,
      speed: 10,
      luck: 2,
      defence: 3,
      resistance: 8,
      move: 6,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 5,
      magic: 15,
      skill: 5,
      speed: 20,
      luck: 0,
      defence: 0,
      resistance: 20,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "A",
      WeaponRankStaffRod: "B",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 50,
      strength: 27,
      magic: 31,
      skill: 27,
      speed: 34,
      luck: 27,
      defence: 25,
      resistance: 34,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 4,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 2,
      move: 1,
    },
  },
  {
    className: "Wyvern Rider",
    classTree: [],
    promotionStatus: false,
    description:
      "Knights who fight astride a wyvern. Has superior strength and defence.",
    TypeProperty: ["Dragon", "Flying"],
    parallelClass: null,
    classBaseStats: {
      hp: 17,
      strength: 6,
      magic: 0,
      skill: 5,
      speed: 4,
      luck: 2,
      defence: 7,
      resistance: 0,
      move: 7,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 15,
      magic: 5,
      skill: 10,
      speed: 10,
      luck: 5,
      defence: 20,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "B",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 40,
      strength: 22,
      magic: 17,
      skill: 21,
      speed: 20,
      luck: 19,
      defence: 24,
      resistance: 15,
    },
    classPairUpBonuses: {
      strength: 3,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 3,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Wyvern Lord",
    classTree: [],
    promotionStatus: true,
    description:
      "High-ranking wyvern riders. With their axes and lances, they demolish enemy forces.",
    TypeProperty: ["Dragon", "Flying"],
    classBaseStats: {
      hp: 19,
      strength: 8,
      magic: 0,
      skill: 9,
      speed: 6,
      luck: 3,
      defence: 10,
      resistance: 1,
      move: 8,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 15,
      magic: 0,
      skill: 15,
      speed: 10,
      luck: 5,
      defence: 20,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "B",
      WeaponRankAxeClub: "A",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 60,
      strength: 33,
      magic: 25,
      skill: 33,
      speed: 29,
      luck: 28,
      defence: 35,
      resistance: 26,
    },
    classPairUpBonuses: {
      strength: 3,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 3,
      resistance: 0,
      move: 1,
    },
  },
  {
    className: "Malig Knight",
    classTree: [],
    promotionStatus: true,
    description:
      "Knights who command a mage dragon. With their axes and magic, they trample over enemy forces.",
    TypeProperty: ["Dragon", "Flying"],
    classBaseStats: {
      hp: 18,
      strength: 7,
      magic: 6,
      skill: 6,
      speed: 5,
      luck: 0,
      defence: 8,
      resistance: 6,
      move: 8,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 15,
      magic: 15,
      skill: 10,
      speed: 5,
      luck: 0,
      defence: 10,
      resistance: 15,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "A",
      WeaponRankTomeScroll: "B",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 55,
      strength: 31,
      magic: 30,
      skill: 28,
      speed: 27,
      luck: 25,
      defence: 31,
      resistance: 31,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 2,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 2,
      resistance: 2,
      move: 1,
    },
  },
  {
    className: "Dark Mage",
    classTree: [],
    promotionStatus: false,
    description:
      "Sorcerers who have learned Nohrian magic. They attack enemies with magic.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 16,
      strength: 0,
      magic: 6,
      skill: 3,
      speed: 3,
      luck: 1,
      defence: 3,
      resistance: 5,
      move: 5,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 10,
      magic: 20,
      skill: 0,
      speed: 10,
      luck: 0,
      defence: 5,
      resistance: 10,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "B",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 35,
      strength: 19,
      magic: 24,
      skill: 16,
      speed: 19,
      luck: 18,
      defence: 19,
      resistance: 22,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 3,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 3,
      move: 0,
    },
  },
  {
    className: "Sorcerer",
    classTree: [],
    promotionStatus: true,
    description:
      "High-ranking sorcerers who have reached the esoteric pinnacle. They possess exceptional magic.",
    TypeProperty: [],
    classBaseStats: {
      hp: 17,
      strength: 0,
      magic: 9,
      skill: 4,
      speed: 6,
      luck: 1,
      defence: 5,
      resistance: 8,
      move: 6,
      BonusCrit: 10,
      BonusCritAvoid: 5,
      BonusHit: 5,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 0,
      magic: 25,
      skill: 0,
      speed: 10,
      luck: 0,
      defence: 5,
      resistance: 15,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "S",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 50,
      strength: 25,
      magic: 35,
      skill: 26,
      speed: 29,
      luck: 26,
      defence: 29,
      resistance: 33,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 5,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 3,
      move: 0,
    },
  },
  {
    className: "Dark Knight",
    classTree: [],
    promotionStatus: true,
    description:
      "Magic knights whose bodies are infused with sorcery. They're capable of harnessing swords and magic.",
    TypeProperty: ["Beast"],
    classBaseStats: {
      hp: 19,
      strength: 8,
      magic: 6,
      skill: 6,
      speed: 5,
      luck: 3,
      defence: 8,
      resistance: 6,
      move: 8,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 15,
      strength: 20,
      magic: 10,
      skill: 5,
      speed: 5,
      luck: 5,
      defence: 15,
      resistance: 5,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "B",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "A",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 55,
      strength: 32,
      magic: 31,
      skill: 28,
      speed: 27,
      luck: 31,
      defence: 34,
      resistance: 30,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 3,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 3,
      resistance: 0,
      move: 1,
    },
  },
  {
    className: "Troubadour",
    classTree: [],
    promotionStatus: false,
    description:
      "Staff-wielding knights who are incapable of fighting. Instead, they heal allies with staves.",
    TypeProperty: ["Beast"],
    classBaseStats: {
      hp: 15,
      strength: 0,
      magic: 3,
      skill: 7,
      speed: 5,
      luck: 4,
      defence: 1,
      resistance: 4,
      move: 7,
      BonusCrit: 0,
      BonusCritAvoid: 10,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 0,
      magic: 10,
      skill: 20,
      speed: 10,
      luck: 15,
      defence: 0,
      resistance: 15,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "B",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 35,
      strength: 16,
      magic: 19,
      skill: 24,
      speed: 20,
      luck: 23,
      defence: 16,
      resistance: 21,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 2,
      skill: 0,
      speed: 0,
      luck: 2,
      defence: 0,
      resistance: 2,
      move: 0,
    },
  },
  {
    className: "Strategist",
    classTree: [],
    promotionStatus: true,
    description:
      "Tacticians who command the battlefield from horseback. With their magic and staves, they turn the tide of battle.",
    TypeProperty: ["Beast"],
    classBaseStats: {
      hp: 16,
      strength: 0,
      magic: 7,
      skill: 6,
      speed: 7,
      luck: 5,
      defence: 2,
      resistance: 7,
      move: 8,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 0,
      magic: 15,
      skill: 5,
      speed: 10,
      luck: 20,
      defence: 0,
      resistance: 15,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "B",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "A",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 45,
      strength: 25,
      magic: 33,
      skill: 28,
      speed: 31,
      luck: 33,
      defence: 25,
      resistance: 32,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 2,
      skill: 0,
      speed: 0,
      luck: 2,
      defence: 0,
      resistance: 2,
      move: 1,
    },
  },
  {
    className: "Maid",
    classTree: [],
    promotionStatus: true,
    description:
      "Female vassals who serve a master. They heal their master with staves and protect them with daggers.",
    TypeProperty: [],
    classBaseStats: {
      hp: 18,
      strength: 4,
      magic: 5,
      skill: 9,
      speed: 8,
      luck: 4,
      defence: 5,
      resistance: 4,
      move: 6,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 10,
      magic: 10,
      skill: 15,
      speed: 15,
      luck: 10,
      defence: 5,
      resistance: 10,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "B",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "S",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 50,
      strength: 28,
      magic: 31,
      skill: 33,
      speed: 33,
      luck: 32,
      defence: 29,
      resistance: 29,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 2,
      skill: 0,
      speed: 3,
      luck: 3,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Butler",
    classTree: [],
    promotionStatus: true,
    description:
      "Male vassals who serve a master. They heal their master with staves and protect them with daggers.",
    TypeProperty: [],
    classBaseStats: {
      hp: 18,
      strength: 4,
      magic: 5,
      skill: 9,
      speed: 8,
      luck: 4,
      defence: 5,
      resistance: 4,
      move: 6,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 10,
      magic: 10,
      skill: 15,
      speed: 15,
      luck: 10,
      defence: 5,
      resistance: 10,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "B",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "S",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 50,
      strength: 28,
      magic: 31,
      skill: 33,
      speed: 33,
      luck: 32,
      defence: 29,
      resistance: 29,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 2,
      skill: 0,
      speed: 3,
      luck: 3,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Wolfskin",
    classTree: [],
    promotionStatus: false,
    description:
      "A werewolf said to feast on the flesh of humans. Has excellent strength and speed.",
    TypeProperty: ["Beast"],
    parallelClass: null,
    classBaseStats: {
      hp: 19,
      strength: 8,
      magic: 0,
      skill: 4,
      speed: 6,
      luck: 0,
      defence: 4,
      resistance: 0,
      move: 5,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 20,
      strength: 20,
      magic: 0,
      skill: 5,
      speed: 15,
      luck: 5,
      defence: 10,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "B",
    },
    MaxStatCaps: {
      hp: 45,
      strength: 24,
      magic: 15,
      skill: 18,
      speed: 22,
      luck: 17,
      defence: 21,
      resistance: 15,
    },
    classPairUpBonuses: {
      strength: 3,
      magic: 0,
      skill: 0,
      speed: 3,
      luck: 0,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Wolfssegner",
    classTree: [],
    promotionStatus: true,
    description:
      "A high-ranking werewolf with a more resilient body. Has better abilities than a Wolfskin.",
    TypeProperty: ["Beast"],
    classBaseStats: {
      hp: 22,
      strength: 11,
      magic: 0,
      skill: 6,
      speed: 7,
      luck: 1,
      defence: 7,
      resistance: 1,
      move: 6,
      BonusCrit: 5,
      BonusCritAvoid: 10,
      BonusHit: 10,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 20,
      strength: 20,
      magic: 0,
      skill: 5,
      speed: 15,
      luck: 5,
      defence: 10,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "S",
    },
    MaxStatCaps: {
      hp: 65,
      strength: 36,
      magic: 25,
      skill: 29,
      speed: 31,
      luck: 26,
      defence: 32,
      resistance: 26,
    },
    classPairUpBonuses: {
      strength: 4,
      magic: 0,
      skill: 0,
      speed: 4,
      luck: 0,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Dread Fighter",
    classTree: [],
    promotionStatus: null,
    description:
      "Those who have learned elusive battle arts. They disorientate foes with katanas, clubs and shurikens.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 19,
      strength: 8,
      magic: 3,
      skill: 6,
      speed: 8,
      luck: 1,
      defence: 6,
      resistance: 9,
      move: 6,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 15,
      strength: 15,
      magic: 5,
      skill: 5,
      speed: 15,
      luck: 0,
      defence: 5,
      resistance: 20,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "A",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "B",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "B",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 55,
      strength: 32,
      magic: 28,
      skill: 29,
      speed: 31,
      luck: 26,
      defence: 29,
      resistance: 34,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 0,
      skill: 0,
      speed: 2,
      luck: 0,
      defence: 0,
      resistance: 4,
      move: 0,
    },
  },
  {
    className: "Dark Falcon",
    classTree: [],
    promotionStatus: null,
    description:
      "Knights who ride astride a pitch-black pegasus. They rush the battlefield armed with lances and tomes.",
    TypeProperty: ["Beast", "Flying"],
    parallelClass: null,
    classBaseStats: {
      hp: 17,
      strength: 4,
      magic: 7,
      skill: 5,
      speed: 9,
      luck: 4,
      defence: 3,
      resistance: 9,
      move: 8,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 0,
      strength: 10,
      magic: 15,
      skill: 5,
      speed: 15,
      luck: 15,
      defence: 0,
      resistance: 20,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "B",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "A",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 45,
      strength: 27,
      magic: 32,
      skill: 28,
      speed: 33,
      luck: 32,
      defence: 26,
      resistance: 34,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 3,
      skill: 0,
      speed: 3,
      luck: 0,
      defence: 0,
      resistance: 0,
      move: 1,
    },
  },
  {
    className: "Ballistician",
    classTree: [],
    promotionStatus: null,
    description:
      "An Outrealm class. Rides a mobile cannon. In addition to bows, it can use cannons to inflict wide damage to enemy troops.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 18,
      strength: 10,
      magic: 0,
      skill: 7,
      speed: 2,
      luck: 4,
      defence: 3,
      resistance: 1,
      move: 4,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 5,
      strength: 25,
      magic: 0,
      skill: 15,
      speed: 0,
      luck: 10,
      defence: 5,
      resistance: 5,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "B",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 50,
      strength: 39,
      magic: 25,
      skill: 31,
      speed: 25,
      luck: 32,
      defence: 27,
      resistance: 26,
    },
    classPairUpBonuses: {
      strength: 3,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 2,
      defence: 1,
      resistance: 1,
      move: 0,
    },
  },
  {
    className: "Witch",
    classTree: [],
    promotionStatus: null,
    description:
      "An Outrealm class. Has the ability to manipulate space. Can teleport great distances in the blink of an eye.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 17,
      strength: 0,
      magic: 10,
      skill: 5,
      speed: 9,
      luck: 3,
      defence: 4,
      resistance: 5,
      move: 6,
      BonusCrit: 10,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 10,
    },
    classGrowths: {
      hp: 5,
      strength: 0,
      magic: 25,
      skill: 5,
      speed: 20,
      luck: 5,
      defence: 0,
      resistance: 10,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "n",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "S",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 50,
      strength: 25,
      magic: 36,
      skill: 27,
      speed: 34,
      luck: 28,
      defence: 26,
      resistance: 29,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 5,
      skill: 0,
      speed: 3,
      luck: 0,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Lodestar",
    classTree: [],
    promotionStatus: null,
    description:
      "An Outrealm class. A legendary hero spoken of in sagas. Fights wielding swords.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 19,
      strength: 7,
      magic: 0,
      skill: 10,
      speed: 9,
      luck: 7,
      defence: 7,
      resistance: 2,
      move: 6,
      BonusCrit: 5,
      BonusCritAvoid: 0,
      BonusHit: 10,
      BonusAvoid: 10,
    },
    classGrowths: {
      hp: 15,
      strength: 10,
      magic: 0,
      skill: 20,
      speed: 10,
      luck: 25,
      defence: 5,
      resistance: 5,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "S",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 60,
      strength: 29,
      magic: 26,
      skill: 35,
      speed: 33,
      luck: 40,
      defence: 30,
      resistance: 29,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 0,
      skill: 0,
      speed: 3,
      luck: 3,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Vanguard",
    classTree: [],
    promotionStatus: null,
    description:
      "An Outrealm class. A commander who fights at the front-lines. Can wield both swords and axes.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 21,
      strength: 10,
      magic: 0,
      skill: 6,
      speed: 7,
      luck: 3,
      defence: 9,
      resistance: 1,
      move: 6,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 20,
      strength: 20,
      magic: 0,
      skill: 5,
      speed: 5,
      luck: 10,
      defence: 15,
      resistance: 0,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "A",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "B",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 65,
      strength: 36,
      magic: 25,
      skill: 29,
      speed: 30,
      luck: 30,
      defence: 32,
      resistance: 27,
    },
    classPairUpBonuses: {
      strength: 5,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 3,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Great Lord",
    classTree: [],
    promotionStatus: null,
    description:
      "An Outrealm class. A powerful royal who leads armies. Can wield lances, in addition to swords.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 18,
      strength: 8,
      magic: 1,
      skill: 8,
      speed: 9,
      luck: 5,
      defence: 7,
      resistance: 3,
      move: 6,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 15,
      strength: 15,
      magic: 0,
      skill: 10,
      speed: 10,
      luck: 15,
      defence: 10,
      resistance: 5,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "A",
      WeaponRankLanceNaginata: "B",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "n",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 60,
      strength: 30,
      magic: 25,
      skill: 32,
      speed: 34,
      luck: 35,
      defence: 29,
      resistance: 31,
    },
    classPairUpBonuses: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 4,
      luck: 4,
      defence: 0,
      resistance: 0,
      move: 0,
    },
  },
  {
    className: "Grandmaster",
    classTree: [],
    promotionStatus: null,
    description:
      "An Outrealm class. A tactician with a gift for commanding troops. Can fight with swords and tomes.",
    TypeProperty: [],
    parallelClass: null,
    classBaseStats: {
      hp: 18,
      strength: 7,
      magic: 6,
      skill: 8,
      speed: 7,
      luck: 2,
      defence: 6,
      resistance: 8,
      move: 6,
      BonusCrit: 0,
      BonusCritAvoid: 0,
      BonusHit: 0,
      BonusAvoid: 0,
    },
    classGrowths: {
      hp: 10,
      strength: 15,
      magic: 15,
      skill: 15,
      speed: 5,
      luck: 0,
      defence: 5,
      resistance: 15,
    },
    classSkills: [],
    MaxWeaponRank: {
      WeaponRankSwordKatana: "B",
      WeaponRankLanceNaginata: "n",
      WeaponRankAxeClub: "n",
      WeaponRankTomeScroll: "A",
      WeaponRankKnifeShuriken: "n",
      WeaponRankBowYumi: "n",
      WeaponRankStaffRod: "n",
      WeaponRankStone: "n",
    },
    MaxStatCaps: {
      hp: 55,
      strength: 31,
      magic: 33,
      skill: 33,
      speed: 29,
      luck: 26,
      defence: 28,
      resistance: 33,
    },
    classPairUpBonuses: {
      strength: 2,
      magic: 2,
      skill: 2,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 2,
      move: 0,
    },
  },
];

// Populates the class tree so that classes know what classes they are related to aka which classes they can directly class change to.
function setClassTree(targetClassName: string, treeClassNames: string[]): void {
  const targetClass = defaultClassData.find(
    (c) => c.className === targetClassName,
  );
  if (!targetClass) {
    console.warn(
      `Target class ${targetClassName} not found in defaultClassData`,
    );
    return;
  }

  const classTree: Class[] = treeClassNames
    .map((name) => {
      const cls = defaultClassData.find((c) => c.className === name);
      if (!cls) {
        console.warn(
          `Class ${name} not found for classTree of ${targetClassName}`,
        );
      }
      return cls;
    })
    .filter((cls): cls is Class => cls !== undefined); // Remove undefined entries

  targetClass.classTree = classTree;
}

export function initializeClassTree(): void {
  //Base classes show their own class and what they can promote to.
  setClassTree("Nohr Prince", ["Nohr Prince", "Nohr Noble", "Hoshido Noble"]);
  setClassTree("Nohr Princess", [
    "Nohr Princess",
    "Nohr Noble",
    "Hoshido Noble",
  ]);

  setClassTree("Samurai", ["Samurai", "Swordmaster", "Master of Arms"]);
  setClassTree("Villager", ["Villager", "Master of Arms", "Merchant"]);
  setClassTree("Ninja", ["Ninja", "Master Ninja", "Mechanist"]);
  setClassTree("Oni Savage", ["Oni Savage", "Oni Chieftain", "Blacksmith"]);
  setClassTree("Spear Fighter", ["Spear Fighter", "Spear Master", "Basara"]);
  setClassTree("Diviner", ["Diviner", "Basara", "Onmyoji"]);
  setClassTree("Monk", ["Monk", "Great Master", "Onmyoji"]);
  setClassTree("Shrine Maiden", ["Shrine Maiden", "Priestess", "Onmyoji"]);
  setClassTree("Sky Knight", ["Sky Knight", "Falcon Knight", "Kinshi Knight"]);
  setClassTree("Archer", ["Archer", "Kinshi Knight", "Sniper"]);
  setClassTree("Kitsune", ["Kitsune", "Nine-Tails"]);

  setClassTree("Cavalier", ["Cavalier", "Paladin", "Great Knight"]);
  setClassTree("Knight", ["Knight", "General", "Great Knight"]);
  setClassTree("Fighter", ["Fighter", "Berserker", "Hero"]);
  setClassTree("Mercenary", ["Mercenary", "Hero", "Bow Knight"]);
  setClassTree("Outlaw", ["Outlaw", "Adventurer", "Bow Knight"]);
  setClassTree("Wyvern Rider", ["Wyvern Rider", "Wyvern Lord", "Malig Knight"]);
  setClassTree("Dark Mage", ["Dark Mage", "Sorcerer", "Dark Knight"]);
  setClassTree("Troubadour", ["Troubadour", "Strategist", "Butler", "Maid"]);
  setClassTree("Wolfskin", ["Wolfskin", "Wolfssegner"]);

  //Promoted classes show which classes could have promoted to them, as well as themselves. Does not show adjacent classes as overlap between classes can cause issues
  setClassTree("Hoshido Noble", [
    "Nohr Prince",
    "Nohr Princess",
    "Hoshido Noble",
  ]);
  setClassTree("Nohr Noble", ["Nohr Prince", "Nohr Princess", "Nohr Noble"]);

  setClassTree("Swordmaster", ["Samurai", "Swordmaster"]);
  setClassTree("Master of Arms", ["Samurai", "Villager", "Master of Arms"]);
  setClassTree("Merchant", ["Villager", "Apothecary", "Merchant"]);
  setClassTree("Mechanist", ["Apothecary", "Ninja", "Mechanist"]);
  setClassTree("Master Ninja", ["Ninja", "Master Ninja"]);
  setClassTree("Oni Chieftain", ["Oni Savage", "Oni Chieftain"]);
  setClassTree("Blacksmith", ["Oni Savage", "Blacksmith"]);
  setClassTree("Spear Master", ["Spear Fighter", "Spear Master"]);
  setClassTree("Basara", ["Spear Fighter", "Diviner", "Basara"]);
  setClassTree("Onmyoji", ["Onmyoji", "Diviner", "Monk", "Shrine Maiden"]);
  setClassTree("Falcon Knight", ["Sky Knight", "Falcon Knight"]);
  setClassTree("Kinshi Knight", ["Sky Knight", "Archer", "Kinshi Knight"]);
  setClassTree("Sniper", ["Archer", "Sniper"]);
  setClassTree("Nine-Tails", ["Kitsune", "Nine-Tails"]);

  setClassTree("Paladin", ["Cavalier", "Paladin"]);
  setClassTree("Great Knight", ["Cavalier", "Knight", "Great Knight"]);
  setClassTree("General", ["Knight", "General"]);
  setClassTree("Berserker", ["Fighter", "Berserker"]);
  setClassTree("Hero", ["Fighter", "Mercenary", "Hero"]);
  setClassTree("Bow Knight", ["Mercenary", "Outlaw", "Bow Knight"]);
  setClassTree("Adventurer", ["Outlaw", "Adventurer"]);
  setClassTree("Wyvern Lord", ["Wyvern Rider", "Wyvern Lord"]);
  setClassTree("Malig Knight", ["Wyvern Rider", "Malig Knight"]);
  setClassTree("Sorcerer", ["Dark Mage", "Sorcerer"]);
  setClassTree("Dark Knight", ["Dark Mage", "Dark Knight"]);
  setClassTree("Strategist", ["Troubadour", "Strategist"]);
  setClassTree("Butler", ["Troubadour", "Butler"]);
  setClassTree("Maid", ["Troubadour", "Maid"]);
  setClassTree("Wolfssegner", ["Wolfskin", "Wolfssegner"]);
}

//Similar as above. Parallel classes are obtained rarely through a unit gaining nothing from a partner/friendship/parent class set
function setParallelClass(
  targetClassName: string,
  parallelClassName: string,
): void {
  const targetClass = defaultClassData.find(
    (c) => c.className === targetClassName,
  );
  if (!targetClass) {
    console.warn(
      `Target class ${targetClassName} not found in defaultClassData`,
    );
    return;
  }

  const parallelClass = defaultClassData.find(
    (c) => c.className === parallelClassName,
  );
  if (!parallelClass) {
    console.warn(
      `Parallel class ${parallelClassName} not found for ${targetClassName}`,
    );
    return;
  }

  targetClass.parallelClass = parallelClass;
}

export function initializeParallelClasses(): void {
  setParallelClass("Cavalier", "Ninja");
  setParallelClass("Knight", "Spear Fighter");
  setParallelClass("Fighter", "Oni Savage");
  setParallelClass("Mercenary", "Samurai");
  setParallelClass("Outlaw", "Archer");
  setParallelClass("Samurai", "Mercenary");
  setParallelClass("Oni Savage", "Fighter");
  setParallelClass("Spear Fighter", "Knight");
  setParallelClass("Diviner", "Dark Mage");
  setParallelClass("Sky Knight", "Wyvern Rider");
  setParallelClass("Archer", "Outlaw");
  setParallelClass("Wyvern Rider", "Sky Knight");
  setParallelClass("Ninja", "Cavalier");
  setParallelClass("Dark Mage", "Diviner");
  setParallelClass("Wolfskin", "Outlaw");
  setParallelClass("Kitsune", "Apothecary");
  setParallelClass("Songstress", "Troubadour");
  setParallelClass("Villager", "Apothecary");
}

// Set classSkills for a specific class. Does through function after, as circular reference causes issues.
export function setClassSkills(className: string, skillNames: string[]): void {
  const targetClass = defaultClassData.find((c) => c.className === className);
  if (!targetClass) {
    console.warn(`Class ${className} not found in defaultClassData`);
    return;
  }

  const skills = skillNames
    .map((name) => {
      const skill = getSkill(name);
      if (skill.name === "Unknown") {
        console.warn(`Skill ${name} not found for class ${className}`);
      }
      return skill;
    })
    .filter((skill) => skill.name !== "Unknown");

  targetClass.classSkills = skills;
}

export function initializeClassSkills(): void {
  setClassSkills("Nohr Prince", ["Nobility", "Dragon Fang"]);
  setClassSkills("Nohr Princess", ["Nobility", "Dragon Fang"]);
  setClassSkills("Hoshido Noble", ["Dragon Ward", "Hoshidan Unity"]);
  setClassSkills("Samurai", ["Duelist's Blow", "Vantage"]);
  setClassSkills("Swordmaster", ["Astra", "Swordfaire"]);
  setClassSkills("Master of Arms", ["Seal Strength", "Life and Death"]);
  setClassSkills("Oni Savage", ["Seal Resistance", "Shove"]);
  setClassSkills("Oni Chieftain", ["Death Blow", "Counter"]);
  setClassSkills("Blacksmith", ["Salvage Blow", "Lancebreaker"]);
  setClassSkills("Spear Fighter", ["Seal Defence", "Swap"]);
  setClassSkills("Spear Master", ["Seal Speed", "Lancefaire"]);
  setClassSkills("Basara", ["Rend Heaven", "Quixotic"]);
  setClassSkills("Diviner", ["Magic +2", "Future Sight"]);
  setClassSkills("Onmyoji", ["Rally Magic", "Tomefaire"]);
  setClassSkills("Shrine Maiden", ["Miracle", "Rally Luck"]);
  setClassSkills("Monk", ["Miracle", "Rally Luck"]);
  setClassSkills("Priestess", ["Renewal", "Countermagic"]);
  setClassSkills("Great Master", ["Renewal", "Countermagic"]);
  setClassSkills("Sky Knight", ["Darting Blow", "Camaraderie"]);
  setClassSkills("Falcon Knight", ["Rally Speed", "Warding Blow"]);
  setClassSkills("Kinshi Knight", ["Air Superiority", "Amaterasu"]);
  setClassSkills("Archer", ["Skill +2", "Quick Draw"]);
  setClassSkills("Sniper", ["Certain Blow", "Bowfaire"]);
  setClassSkills("Ninja", ["Locktouch", "Poison Strike"]);
  setClassSkills("Master Ninja", ["Lethality", "Shurikenfaire"]);
  setClassSkills("Mechanist", ["Golembane", "Replicate"]);
  setClassSkills("Apothecary", ["Potent Potion", "Quick Salve"]);
  setClassSkills("Merchant", ["Profiteer", "Spendthrift"]);
  setClassSkills("Kitsune", ["Evenhanded", "Beastbane"]);
  setClassSkills("Nine-Tails", ["Even Better", "Grisly Wound"]);
  setClassSkills("Songstress", [
    "Luck +4",
    "Inspiring Song",
    "Voice of Peace",
    "Foreign Princess",
  ]);
  setClassSkills("Villager", ["Aptitude", "Underdog"]);
  setClassSkills("Nohr Noble", ["Draconic Hex", "Nohrian Trust"]);
  setClassSkills("Cavalier", ["Elbow Room", "Shelter"]);
  setClassSkills("Paladin", ["Defender", "Aegis"]);
  setClassSkills("Great Knight", ["Luna", "Armored Blow"]);
  setClassSkills("Knight", ["Defence +2", "Natural Cover"]);
  setClassSkills("General", ["Wary Fighter", "Pavise"]);
  setClassSkills("Fighter", ["HP +5", "Gamble"]);
  setClassSkills("Berserker", ["Rally Strength", "Axefaire"]);
  setClassSkills("Mercenary", ["Good Fortune", "Strong Riposte"]);
  setClassSkills("Hero", ["Sol", "Axebreaker"]);
  setClassSkills("Bow Knight", ["Rally Skill", "Shurikenbreaker"]);
  setClassSkills("Outlaw", ["Movement +1", "Lucky Seven"]);
  setClassSkills("Adventurer", ["Pass"]);
  setClassSkills("Wyvern Rider", ["Strength +2", "Lunge"]);
  setClassSkills("Wyvern Lord", ["Rally Defence", "Swordbreaker"]);
  setClassSkills("Malig Knight", ["Savage Blow", "Trample"]);
  setClassSkills("Dark Mage", ["Heartseeker", "Malefic Aura"]);
  setClassSkills("Sorcerer", ["Vengeance", "Bowbreaker"]);
  setClassSkills("Dark Knight", ["Seal Magic", "Lifetaker"]);
  setClassSkills("Troubadour", ["Resistance +2", "Gentilhomme", "Demoiselle"]);
  setClassSkills("Strategist", ["Rally Resistance", "Inspiration"]);
  setClassSkills("Maid", ["Live to Serve", "Tomebreaker"]);
  setClassSkills("Butler", ["Live to Serve", "Tomebreaker"]);
  setClassSkills("Wolfskin", ["Odd Shaped", "Beastbane"]);
  setClassSkills("Wolfssegner", ["Better Odds", "Grisly Wound"]);
  setClassSkills("Dread Fighter", [
    "Even Keel",
    "Iron Will",
    "Clarity",
    "Aggressor",
  ]);
  setClassSkills("Sky Knight", ["Speed +2", "Relief"]);
  setClassSkills("Dark Falcon", ["Rally Movement", "Galeforce"]);
  setClassSkills("Ballistician", [
    "Survey",
    "Opportunity Shot",
    "Rifled Barrel",
    "Surefooted",
  ]);
  setClassSkills("Witch", ["Shadowgift", "Witch's Brew", "Warp", "Toxic Brew"]);
  setClassSkills("Lodestar", [
    "Dancing Blade",
    "Charm",
    "Dual Guarder",
    "Speedtaker",
  ]);
  setClassSkills("Vanguard", [
    "Heavy Blade",
    "Veteran Intuition",
    "Aether",
    "Strengthtaker",
  ]);
  setClassSkills("Great Lord", ["Dual Striker", "Awakening"]);
  setClassSkills("Grandmaster", [
    "Tactical Advice",
    "Solidarity",
    "Ignis",
    "Rally Spectrum",
  ]);
}

export const getClass = (name: string): Class => {
  const cls = defaultClassData.find((c) => c.className === name);
  if (!cls) {
    console.warn(`Class ${name} not found`);
    return {
      className: "Unknown",
      classTree: [],
      promotionStatus: null,
      description: "",
      TypeProperty: [],
      classBaseStats: {
        hp: 0,
        strength: 0,
        magic: 0,
        skill: 0,
        speed: 0,
        luck: 0,
        defence: 0,
        resistance: 0,
        move: 0,
        BonusCrit: 0,
        BonusCritAvoid: 0,
        BonusHit: 0,
        BonusAvoid: 0,
      },
      classGrowths: {
        hp: 0,
        strength: 0,
        magic: 0,
        skill: 0,
        speed: 0,
        luck: 0,
        defence: 0,
        resistance: 0,
      },
      classSkills: [],
      MaxWeaponRank: {
        WeaponRankSwordKatana: "n",
        WeaponRankLanceNaginata: "n",
        WeaponRankAxeClub: "n",
        WeaponRankTomeScroll: "n",
        WeaponRankKnifeShuriken: "n",
        WeaponRankBowYumi: "n",
        WeaponRankStaffRod: "n",
        WeaponRankStone: "n",
      },
      MaxStatCaps: {
        hp: 0,
        strength: 0,
        magic: 0,
        skill: 0,
        speed: 0,
        luck: 0,
        defence: 0,
        resistance: 0,
      },
      classPairUpBonuses: {
        strength: 0,
        magic: 0,
        skill: 0,
        speed: 0,
        luck: 0,
        defence: 0,
        resistance: 0,
        move: 0,
      },
    };
  }
  return cls;
};
