import { Character } from "../../types/Fire Emblem Fates/UnitStruct.tsx";
import { defaultClassData } from "./defaultClassData.tsx";
import { defaultSkills } from "./defaultSkills.tsx";
import { Class } from "../../types/Fire Emblem Fates/ClassStruct.tsx";
import { Skill } from "../../types/Fire Emblem Fates/SkillStruct.tsx";

const getClass = (name: string): Class => {
  const cls = defaultClassData.find((c) => c.className === name);
  if (!cls) throw new Error(`Class ${name} not found`);
  return cls;
};

export function getSkill(skillName: string): Skill {
  const skill = defaultSkills.find((s) => s.name === skillName);
  if (!skill) {
    console.warn(`Skill ${skillName} not found in defaultSkills`);
    return defaultSkills[-1];
  }
  return skill;
}

export const defaultCharactersConquest: Character[] = [
  {
    name: "Corrin (M)",
    gender: "M",
    title: "Crux of Fate",
    class: getClass("Nohr Prince"),
    baseInternalLevel: 0,
    royalty_status: true,
    level: 1,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 1, getClass("Nohr Prince")]],
    starting_weapons: [],
    stats: {
      hp: 19,
      strength: 7,
      magic: 4,
      skill: 7,
      speed: 6,
      luck: 5,
      defence: 6,
      resistance: 2,
      move: 5,
    },
    base_growths: {
      hp: 45,
      strength: 45,
      magic: 30,
      skill: 40,
      speed: 45,
      luck: 45,
      defence: 35,
      resistance: 25,
    },
    personal_skill: getSkill("Supportive"),
    equipped_skills: [
      getSkill("Nobility"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Nobility")],
    base_class_set: {
      starting_class: getClass("Nohr Prince"),
      starting_class_tree: getClass("Nohr Prince"),
      heart_seal_classes: [],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    boon: "None selected yet",
    bane: "None selected yet",
    RouteAvailability: "Prologue",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "D",
    },
    maxStatModifiers: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
  },
  {
    name: "Corrin (F)",
    gender: "F",
    title: "Crux of Fate",
    class: getClass("Nohr Princess"),
    baseInternalLevel: 0,
    royalty_status: true,
    level: 1,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 1, getClass("Nohr Princess")]],
    starting_weapons: [],
    stats: {
      hp: 19,
      strength: 7,
      magic: 4,
      skill: 7,
      speed: 6,
      luck: 5,
      defence: 6,
      resistance: 2,
      move: 5,
    },
    base_growths: {
      hp: 45,
      strength: 45,
      magic: 30,
      skill: 40,
      speed: 45,
      luck: 45,
      defence: 35,
      resistance: 25,
    },
    personal_skill: getSkill("Supportive"),
    equipped_skills: [
      getSkill("Nobility"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Nobility")],
    base_class_set: {
      starting_class: getClass("Nohr Princess"),
      starting_class_tree: getClass("Nohr Princess"),
      heart_seal_classes: [],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    boon: "None selected yet",
    bane: "None selected yet",
    RouteAvailability: "Prologue",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "D",
    },
    maxStatModifiers: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
  },
  // This is for female Corrin, where Jakob appears as the first partner at lvl1. Changes to lvl 13 otherwise on male Corrin. Same rules apply for Felicia, in reverse.
  {
    name: "Jakob",
    gender: "M",
    title: "Devoted Servant",
    royalty_status: false,
    class: getClass("Butler"),
    baseInternalLevel: 0,
    level: 1,
    eternalSealCount: 0,
    maxLevelModifier: 40,
    class_line: [[0, 1, getClass("Butler")]],
    starting_weapons: ["Iron Dagger", "Heal"],
    stats: {
      hp: 21,
      strength: 8,
      magic: 6,
      skill: 12,
      speed: 9,
      luck: 10,
      defence: 7,
      resistance: 6,
      move: 6,
    },
    base_growths: {
      hp: 50,
      strength: 30,
      magic: 15,
      skill: 40,
      speed: 35,
      luck: 45,
      defence: 25,
      resistance: 25,
    },
    personal_skill: getSkill("Evasive Partner"),
    equipped_skills: [
      getSkill("Resistance +2"),
      getSkill("Gentilhomme"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Resistance +2"), getSkill("Gentilhomme")],
    base_class_set: {
      starting_class: getClass("Butler"),
      starting_class_tree: getClass("Troubadour"),
      heart_seal_classes: [getClass("Cavalier")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 2",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "D",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "D",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 2,
      magic: -2,
      skill: 2,
      speed: 0,
      luck: -1,
      defence: 0,
      resistance: -1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 1,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 3,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
  },
  {
    // second version of jakob as discussed above
    name: "Jakob",
    gender: "M",
    title: "Devoted Servant",
    royalty_status: false,
    class: getClass("Butler"),
    baseInternalLevel: 0,
    level: 13,
    eternalSealCount: 0,
    maxLevelModifier: 40,
    class_line: [[0, 13, getClass("Butler")]],
    starting_weapons: [],
    stats: {
      hp: 27,
      strength: 13,
      magic: 9,
      skill: 19,
      speed: 15,
      luck: 17,
      defence: 11,
      resistance: 10,
      move: 6,
    },
    base_growths: {
      hp: 50,
      strength: 30,
      magic: 15,
      skill: 40,
      speed: 35,
      luck: 45,
      defence: 25,
      resistance: 25,
    },
    personal_skill: getSkill("Evasive Partner"),
    equipped_skills: [
      getSkill("Resistance +2"),
      getSkill("Gentilhomme"),
      getSkill("Live to Serve"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [
      getSkill("Resistance +2"),
      getSkill("Gentilhomme"),
      getSkill("Live to Serve"),
    ],
    base_class_set: {
      starting_class: getClass("Butler"),
      starting_class_tree: getClass("Troubadour"),
      heart_seal_classes: [getClass("Cavalier")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 16",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "C",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "C",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 2,
      magic: -2,
      skill: 2,
      speed: 0,
      luck: -1,
      defence: 0,
      resistance: -1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 1,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 3,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
  },
  {
    name: "Felicia",
    gender: "F",
    title: "Maid Mayhem",
    royalty_status: false,
    class: getClass("Maid"),
    baseInternalLevel: 0,
    level: 1,
    eternalSealCount: 0,
    maxLevelModifier: 40,
    class_line: [[0, 1, getClass("Maid")]],
    starting_weapons: ["Iron Dagger", "Heal"],
    stats: {
      hp: 19,
      strength: 5,
      magic: 9,
      skill: 10,
      speed: 10,
      luck: 12,
      defence: 5,
      resistance: 9,
      move: 6,
    },
    base_growths: {
      hp: 40,
      strength: 10,
      magic: 35,
      skill: 30,
      speed: 40,
      luck: 55,
      defence: 15,
      resistance: 35,
    },
    personal_skill: getSkill("Devoted Partner"),
    equipped_skills: [
      getSkill("Resistance +2"),
      getSkill("Demoiselle"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Resistance +2"), getSkill("Demoiselle")],
    base_class_set: {
      starting_class: getClass("Maid"),
      starting_class_tree: getClass("Troubadour"),
      heart_seal_classes: [getClass("Mercenary")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 2",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "D",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "D",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: -2,
      magic: 2,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: -1,
      resistance: 1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 1,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 5,
    },
  },
  {
    name: "Felicia",
    gender: "F",
    title: "Maid Mayhem",
    royalty_status: false,
    class: getClass("Maid"),
    baseInternalLevel: 0,
    level: 13,
    eternalSealCount: 0,
    maxLevelModifier: 40,
    class_line: [[0, 13, getClass("Maid")]],
    starting_weapons: [],
    stats: {
      hp: 24,
      strength: 7,
      magic: 14,
      skill: 15,
      speed: 17,
      luck: 20,
      defence: 7,
      resistance: 14,
      move: 6,
    },
    base_growths: {
      hp: 40,
      strength: 10,
      magic: 35,
      skill: 30,
      speed: 40,
      luck: 55,
      defence: 15,
      resistance: 35,
    },
    personal_skill: getSkill("Devoted Partner"),
    equipped_skills: [
      getSkill("Resistance +2"),
      getSkill("Demoiselle"),
      getSkill("Live to Serve"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [
      getSkill("Resistance +2"),
      getSkill("Demoiselle"),
      getSkill("Live to Serve"),
    ],
    base_class_set: {
      starting_class: getClass("Maid"),
      starting_class_tree: getClass("Troubadour"),
      heart_seal_classes: [getClass("Mercenary")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 16",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "C",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "C",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: -2,
      magic: 2,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: -1,
      resistance: 1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 1,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 5,
    },
  },
  {
    name: "Kaze",
    gender: "M",
    title: "Easygoing Ninja",
    royalty_status: false,
    class: getClass("Ninja"),
    baseInternalLevel: 0,
    level: 9,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 9, getClass("Ninja")]],
    starting_weapons: ["Iron Shuriken", "Vulnerary"],
    stats: {
      hp: 22,
      strength: 9,
      magic: 0,
      skill: 12,
      speed: 16,
      luck: 6,
      defence: 7,
      resistance: 13,
      move: 5,
    },
    base_growths: {
      hp: 55,
      strength: 40,
      magic: 0,
      skill: 45,
      speed: 65,
      luck: 20,
      defence: 20,
      resistance: 35,
    },
    personal_skill: getSkill("Miraculous Save"),
    equipped_skills: [
      getSkill("Locktouch"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Locktouch")],
    base_class_set: {
      starting_class: getClass("Ninja"),
      starting_class_tree: getClass("Ninja"),
      heart_seal_classes: [getClass("Samurai")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 11",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "C",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: -2,
      magic: 0,
      skill: 2,
      speed: 3,
      luck: -2,
      defence: -1,
      resistance: 1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 5,
    },
  },
  {
    name: "Azura",
    gender: "F",
    title: "Lady of the Lake",
    royalty_status: true,
    class: getClass("Songstress"),
    baseInternalLevel: 0,
    level: 1,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 1, getClass("Songstress")]],
    starting_weapons: ["Vulnerary", "Chest Key"],
    stats: {
      hp: 16,
      strength: 5,
      magic: 2,
      skill: 8,
      speed: 8,
      luck: 6,
      defence: 4,
      resistance: 7,
      move: 5,
    },
    base_growths: {
      hp: 25,
      strength: 50,
      magic: 25,
      skill: 60,
      speed: 60,
      luck: 40,
      defence: 15,
      resistance: 35,
    },
    personal_skill: getSkill("Healing Descant"),
    equipped_skills: [
      getSkill("Luck +4"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Luck +4")],
    base_class_set: {
      starting_class: getClass("Songstress"),
      starting_class_tree: getClass("Songstress"),
      heart_seal_classes: [getClass("Sky Knight")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 9",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 3,
      luck: 0,
      defence: -3,
      resistance: 0,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 1,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 5,
    },
  },
  {
    name: "Silas",
    gender: "M",
    title: "Loyal Knight",
    royalty_status: false,
    class: getClass("Cavalier"),
    baseInternalLevel: 0,
    level: 6,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 6, getClass("Cavalier")]],
    starting_weapons: ["Iron Sword", "Bronze Lance"],
    stats: {
      hp: 22,
      strength: 11,
      magic: 0,
      skill: 9,
      speed: 8,
      luck: 7,
      defence: 10,
      resistance: 5,
      move: 7,
    },
    base_growths: {
      hp: 40,
      strength: 45,
      magic: 5,
      skill: 50,
      speed: 40,
      luck: 40,
      defence: 40,
      resistance: 25,
    },
    personal_skill: getSkill("Vow of Friendship"),
    equipped_skills: [
      getSkill("Elbow Room"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Elbow Room")],
    base_class_set: {
      starting_class: getClass("Cavalier"),
      starting_class_tree: getClass("Cavalier"),
      heart_seal_classes: [getClass("Mercenary")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 7",
    weapon_ranks: {
      WeaponRankSwordKatana: "D",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 1,
      magic: 0,
      skill: 2,
      speed: 0,
      luck: -1,
      defence: 0,
      resistance: -1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 1,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_B: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
  },
  {
    name: "Shura",
    gender: "M",
    title: "Righteous Rebel",
    royalty_status: false,
    class: getClass("Adventurer"),
    baseInternalLevel: 20,
    level: 2,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[20, 2, getClass("Adventurer")]],
    starting_weapons: ["Killer Bow", "Mend"],
    stats: {
      hp: 31,
      strength: 18,
      magic: 10,
      skill: 21,
      speed: 24,
      luck: 13,
      defence: 13,
      resistance: 21,
      move: 6,
    },
    base_growths: {
      hp: 30,
      strength: 25,
      magic: 10,
      skill: 20,
      speed: 35,
      luck: 30,
      defence: 15,
      resistance: 35,
    },
    personal_skill: getSkill("Highwayman"),
    equipped_skills: [
      getSkill("Locktouch"),
      getSkill("Movement +1"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Locktouch"), getSkill("Movement +1")],
    base_class_set: {
      starting_class: getClass("Adventurer"),
      starting_class_tree: getClass("Outlaw"),
      heart_seal_classes: [getClass("Ninja"), getClass("Fighter")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 16",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "C",
      WeaponRankStaffRod: "B",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: -1,
      magic: 0,
      skill: -1,
      speed: 3,
      luck: -1,
      defence: -2,
      resistance: 2,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 5,
    },
  },
  {
    name: "Mozu",
    gender: "F",
    title: "Rural Power",
    royalty_status: false,
    class: getClass("Villager"),
    baseInternalLevel: 0,
    level: 1,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 1, getClass("Villager")]],
    starting_weapons: ["Brass Naginata", "Vulnerary"],
    stats: {
      hp: 16,
      strength: 6,
      magic: 0,
      skill: 5,
      speed: 7,
      luck: 3,
      defence: 4,
      resistance: 1,
      move: 5,
    },
    base_growths: {
      hp: 30,
      strength: 40,
      magic: 5,
      skill: 50,
      speed: 55,
      luck: 45,
      defence: 35,
      resistance: 30,
    },
    personal_skill: getSkill("Forager"),
    equipped_skills: [
      getSkill("Aptitude"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Aptitude")],
    base_class_set: {
      starting_class: getClass("Villager"),
      starting_class_tree: getClass("Villager"),
      heart_seal_classes: [getClass("Archer")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Paralogue 1",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 1,
      luck: 1,
      defence: 0,
      resistance: -2,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 1,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 1,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 5,
      Avoid: 0,
    },
  },
  {
    name: "Izana",
    gender: "M",
    title: "Lord of Leisure",
    royalty_status: false,
    class: getClass("Onmyoji"),
    baseInternalLevel: 20,
    level: 5,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[20, 5, getClass("Onmyoji")]],
    starting_weapons: [],
    stats: {
      hp: 31,
      strength: 8,
      magic: 23,
      skill: 25,
      speed: 18,
      luck: 17,
      defence: 14,
      resistance: 24,
      move: 6,
    },
    base_growths: {
      hp: 45,
      strength: 15,
      magic: 35,
      skill: 55,
      speed: 30,
      luck: 45,
      defence: 35,
      resistance: 35,
    },
    personal_skill: getSkill("Peacebringer"),
    equipped_skills: [
      getSkill("Miracle"),
      getSkill("Rally Luck"),
      getSkill("Rally Magic"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [
      getSkill("Miracle"),
      getSkill("Rally Luck"),
      getSkill("Rally Magic"),
    ],
    base_class_set: {
      starting_class: getClass("Onmyoji"),
      starting_class_tree: getClass("Monk"),
      heart_seal_classes: [getClass("Samurai"), getClass("Apothecary")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 23; After upgrading Hot Spring to level 3",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "B",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "C",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 0,
      magic: 1,
      skill: 1,
      speed: -2,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 1,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 1,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
  },
  {
    name: "Gunter",
    gender: "M",
    title: "Inveterate Soldier",
    royalty_status: false,
    class: getClass("Great Knight"),
    baseInternalLevel: 5,
    level: 10,
    eternalSealCount: 0,
    maxLevelModifier: 30,
    class_line: [[5, 10, getClass("Great Knight")]],
    starting_weapons: ["Steel Lance", "Steel Axe", "Javelin", "Vulnerary"],
    stats: {
      hp: 34,
      strength: 17,
      magic: 0,
      skill: 24,
      speed: 10,
      luck: 13,
      defence: 20,
      resistance: 6,
      move: 7,
    },
    base_growths: {
      hp: 15,
      strength: 5,
      magic: 0,
      skill: 5,
      speed: 0,
      luck: 15,
      defence: 5,
      resistance: 5,
    },
    personal_skill: getSkill("Forceful Partner"),
    equipped_skills: [
      getSkill("Elbow Room"),
      getSkill("Shelter"),
      getSkill("Luna"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [
      getSkill("Elbow Room"),
      getSkill("Shelter"),
      getSkill("Luna"),
    ],
    base_class_set: {
      starting_class: getClass("Great Knight"),
      starting_class_tree: getClass("Cavalier"),
      heart_seal_classes: [getClass("Mercenary"), getClass("Wyvern Rider")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 15",
    weapon_ranks: {
      WeaponRankSwordKatana: "D",
      WeaponRankLanceNaginata: "B",
      WeaponRankAxeClub: "C",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 2,
      magic: 0,
      skill: 1,
      speed: -2,
      luck: 0,
      defence: 2,
      resistance: -2,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 1,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 1,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
  },
  {
    name: "Elise",
    gender: "F",
    title: "Budding Flower",
    royalty_status: true,
    class: getClass("Troubadour"),
    baseInternalLevel: 0,
    level: 5,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 5, getClass("Troubadour")]],
    starting_weapons: ["Heal", "Freeze"],
    stats: {
      hp: 19,
      strength: 2,
      magic: 11,
      skill: 5,
      speed: 10,
      luck: 14,
      defence: 4,
      resistance: 11,
      move: 7,
    },
    base_growths: {
      hp: 30,
      strength: 5,
      magic: 65,
      skill: 25,
      speed: 55,
      luck: 70,
      defence: 15,
      resistance: 40,
    },
    personal_skill: getSkill("Lily's Poise"),
    equipped_skills: [
      getSkill("Resistance +2"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Resistance +2")],
    base_class_set: {
      starting_class: getClass("Troubadour"),
      starting_class_tree: getClass("Troubadour"),
      heart_seal_classes: [getClass("Wyvern Rider")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 7",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "D",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: -1,
      magic: 3,
      skill: -2,
      speed: 1,
      luck: 1,
      defence: -3,
      resistance: 1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 1,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 1,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 1,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 1,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 5,
      Avoid: 0,
    },
  },
  {
    name: "Arthur",
    gender: "M",
    title: "Hapless Hero",
    royalty_status: false,
    class: getClass("Fighter"),
    baseInternalLevel: 0,
    level: 7,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 7, getClass("Fighter")]],
    starting_weapons: ["Iron Axe", "Hand Axe"],
    stats: {
      hp: 24,
      strength: 12,
      magic: 0,
      skill: 9,
      speed: 8,
      luck: 1,
      defence: 9,
      resistance: 4,
      move: 5,
    },
    base_growths: {
      hp: 50,
      strength: 45,
      magic: 0,
      skill: 55,
      speed: 35,
      luck: 5,
      defence: 45,
      resistance: 20,
    },
    personal_skill: getSkill("Misfortunate"),
    equipped_skills: [
      getSkill("HP +5"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("HP +5")],
    base_class_set: {
      starting_class: getClass("Fighter"),
      starting_class_tree: getClass("Fighter"),
      heart_seal_classes: [getClass("Cavalier")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 7",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "D",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 1,
      magic: 0,
      skill: 3,
      speed: 0,
      luck: -3,
      defence: 1,
      resistance: -1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 0,
      skill: 2,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
  },
  {
    name: "Effie",
    gender: "F",
    title: "Army of One",
    royalty_status: false,
    class: getClass("Knight"),
    baseInternalLevel: 0,
    level: 6,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 6, getClass("Knight")]],
    starting_weapons: ["Iron Lance"],
    stats: {
      hp: 23,
      strength: 13,
      magic: 0,
      skill: 8,
      speed: 5,
      luck: 10,
      defence: 12,
      resistance: 4,
      move: 4,
    },
    base_growths: {
      hp: 35,
      strength: 60,
      magic: 0,
      skill: 35,
      speed: 50,
      luck: 50,
      defence: 35,
      resistance: 30,
    },
    personal_skill: getSkill("Puissance"),
    equipped_skills: [
      getSkill("Defence +2"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Defence +2")],
    base_class_set: {
      starting_class: getClass("Knight"),
      starting_class_tree: getClass("Knight"),
      heart_seal_classes: [getClass("Troubadour")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 7",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "D",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 3,
      magic: 0,
      skill: -1,
      speed: 1,
      luck: 0,
      defence: -1,
      resistance: -1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 1,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 2,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 6,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
  },
  {
    name: "Odin",
    gender: "M",
    title: "Aching Blood",
    royalty_status: false,
    class: getClass("Dark Mage"),
    baseInternalLevel: 0,
    level: 5,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 5, getClass("Dark Mage")]],
    starting_weapons: ["Thunder", "Vulnerary"],
    stats: {
      hp: 21,
      strength: 5,
      magic: 8,
      skill: 10,
      speed: 7,
      luck: 9,
      defence: 6,
      resistance: 7,
      move: 5,
    },
    base_growths: {
      hp: 55,
      strength: 35,
      magic: 30,
      skill: 55,
      speed: 35,
      luck: 60,
      defence: 40,
      resistance: 20,
    },
    personal_skill: getSkill("Aching Blood"),
    equipped_skills: [
      getSkill("Heartseeker"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Heartseeker")],
    base_class_set: {
      starting_class: getClass("Dark Mage"),
      starting_class_tree: getClass("Dark Mage"),
      heart_seal_classes: [getClass("Samurai")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 8",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "D",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 0,
      magic: 1,
      skill: 1,
      speed: -1,
      luck: 1,
      defence: 0,
      resistance: -1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 1,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 1,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 1,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 3,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
  },
  {
    name: "Niles",
    gender: "M",
    title: "Cruel to Be Kind",
    royalty_status: false,
    class: getClass("Outlaw"),
    baseInternalLevel: 0,
    level: 8,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 8, getClass("Outlaw")]],
    starting_weapons: ["Iron Bow"],
    stats: {
      hp: 22,
      strength: 9,
      magic: 5,
      skill: 9,
      speed: 15,
      luck: 6,
      defence: 7,
      resistance: 12,
      move: 5,
    },
    base_growths: {
      hp: 40,
      strength: 35,
      magic: 20,
      skill: 40,
      speed: 50,
      luck: 30,
      defence: 30,
      resistance: 40,
    },
    personal_skill: getSkill("Kidnap"),
    equipped_skills: [
      getSkill("Locktouch"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Locktouch")],
    base_class_set: {
      starting_class: getClass("Outlaw"),
      starting_class_tree: getClass("Outlaw"),
      heart_seal_classes: [getClass("Dark Mage")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 8",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "D",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: -2,
      magic: 0,
      skill: -1,
      speed: 3,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 1,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_B: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 10,
    },
  },
  {
    name: "Nyx",
    gender: "F",
    title: "Cursed by Youth",
    royalty_status: false,
    class: getClass("Dark Mage"),
    baseInternalLevel: 0,
    level: 9,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 9, getClass("Dark Mage")]],
    starting_weapons: [],
    stats: {
      hp: 20,
      strength: 1,
      magic: 12,
      skill: 5,
      speed: 11,
      luck: 3,
      defence: 4,
      resistance: 8,
      move: 5,
    },
    base_growths: {
      hp: 30,
      strength: 5,
      magic: 50,
      skill: 35,
      speed: 50,
      luck: 20,
      defence: 15,
      resistance: 30,
    },
    personal_skill: getSkill("Countercurse"),
    equipped_skills: [
      getSkill("Heartseeker"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Heartseeker")],
    base_class_set: {
      starting_class: getClass("Dark Mage"),
      starting_class_tree: getClass("Dark Mage"),
      heart_seal_classes: [getClass("Outlaw")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 9",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "C",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 0,
      magic: 3,
      skill: -2,
      speed: 2,
      luck: -1,
      defence: -2,
      resistance: 1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 1,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 1,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 1,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_A: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
  },
  {
    name: "Camilla",
    gender: "F",
    title: "Bewitching Beauty",
    royalty_status: true,
    class: getClass("Malig Knight"),
    baseInternalLevel: 15,
    level: 1,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[15, 1, getClass("Malig Knight")]],
    starting_weapons: ["Steel Axe", "Thunder"],
    stats: {
      hp: 30,
      strength: 19,
      magic: 11,
      skill: 15,
      speed: 19,
      luck: 12,
      defence: 18,
      resistance: 15,
      move: 8,
    },
    base_growths: {
      hp: 40,
      strength: 50,
      magic: 25,
      skill: 50,
      speed: 55,
      luck: 25,
      defence: 35,
      resistance: 45,
    },
    personal_skill: getSkill("Rose's Thorn"),
    equipped_skills: [
      getSkill("Strength +2"),
      getSkill("Lunge"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Strength +2"), getSkill("Lunge")],
    base_class_set: {
      starting_class: getClass("Malig Knight"),
      starting_class_tree: getClass("Wyvern Rider"),
      heart_seal_classes: [getClass("Dark Mage")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 10",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "C",
      WeaponRankTomeScroll: "D",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 1,
      magic: -1,
      skill: 1,
      speed: 1,
      luck: -2,
      defence: 1,
      resistance: 0,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    personal_pair_up_bonuses_A: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 1,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_B: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
  },
  {
    name: "Selena",
    gender: "F",
    title: "Cutting Wit",
    royalty_status: false,
    class: getClass("Mercenary"),
    baseInternalLevel: 0,
    level: 10,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 10, getClass("Mercenary")]],
    starting_weapons: ["Iron Sword", "Bronze Sword", "Vulnerary"],
    stats: {
      hp: 24,
      strength: 12,
      magic: 3,
      skill: 12,
      speed: 15,
      luck: 9,
      defence: 11,
      resistance: 8,
      move: 5,
    },
    base_growths: {
      hp: 40,
      strength: 30,
      magic: 5,
      skill: 25,
      speed: 45,
      luck: 30,
      defence: 45,
      resistance: 30,
    },
    personal_skill: getSkill("Fierce Rival"),
    equipped_skills: [
      getSkill("Good Fortune"),
      getSkill("Strong Riposte"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Good Fortune"), getSkill("Strong Riposte")],
    base_class_set: {
      starting_class: getClass("Mercenary"),
      starting_class_tree: getClass("Mercenary"),
      heart_seal_classes: [getClass("Sky Knight")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 10",
    weapon_ranks: {
      WeaponRankSwordKatana: "D",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: -1,
      magic: 0,
      skill: -1,
      speed: 2,
      luck: 0,
      defence: 1,
      resistance: 0,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 1,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_B: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
  },
  {
    name: "Beruka",
    gender: "F",
    title: "Quiet Assassin",
    royalty_status: false,
    class: getClass("Wyvern Rider"),
    baseInternalLevel: 0,
    level: 9,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 9, getClass("Wyvern Rider")]],
    starting_weapons: ["Iron Axe"],
    stats: {
      hp: 23,
      strength: 13,
      magic: 0,
      skill: 14,
      speed: 9,
      luck: 10,
      defence: 14,
      resistance: 7,
      move: 7,
    },
    base_growths: {
      hp: 45,
      strength: 30,
      magic: 10,
      skill: 55,
      speed: 30,
      luck: 45,
      defence: 40,
      resistance: 25,
    },
    personal_skill: getSkill("Opportunist"),
    equipped_skills: [
      getSkill("Strength +2"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Strength +2")],
    base_class_set: {
      starting_class: getClass("Wyvern Rider"),
      starting_class_tree: getClass("Wyvern Rider"),
      heart_seal_classes: [getClass("Fighter")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 10",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "D",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: -1,
      magic: 0,
      skill: 2,
      speed: -2,
      luck: 0,
      defence: 2,
      resistance: -1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 1,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 1,
      defence: 1,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
  },
  {
    name: "Laslow",
    gender: "M",
    title: "Dancing Duelist",
    royalty_status: false,
    class: getClass("Mercenary"),
    baseInternalLevel: 0,
    level: 12,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 12, getClass("Mercenary")]],
    starting_weapons: ["Steel Sword", "Vulnerary"],
    stats: {
      hp: 28,
      strength: 15,
      magic: 0,
      skill: 16,
      speed: 13,
      luck: 14,
      defence: 10,
      resistance: 7,
      move: 5,
    },
    base_growths: {
      hp: 50,
      strength: 45,
      magic: 0,
      skill: 45,
      speed: 30,
      luck: 55,
      defence: 35,
      resistance: 25,
    },
    personal_skill: getSkill("Fancy Footwork"),
    equipped_skills: [
      getSkill("Good Fortune"),
      getSkill("Strong Riposte"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Good Fortune"), getSkill("Strong Riposte")],
    base_class_set: {
      starting_class: getClass("Mercenary"),
      starting_class_tree: getClass("Mercenary"),
      heart_seal_classes: [getClass("Ninja")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 12",
    weapon_ranks: {
      WeaponRankSwordKatana: "C",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 1,
      magic: 0,
      skill: 2,
      speed: -1,
      luck: 1,
      defence: -1,
      resistance: -1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 1,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 1,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 5,
      Avoid: 0,
    },
  },
  {
    name: "Peri",
    gender: "F",
    title: "Childish Killer",
    royalty_status: false,
    class: getClass("Cavalier"),
    baseInternalLevel: 0,
    level: 10,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 10, getClass("Cavalier")]],
    starting_weapons: ["Steel Lance", "Iron Sword"],
    stats: {
      hp: 25,
      strength: 13,
      magic: 0,
      skill: 9,
      speed: 13,
      luck: 9,
      defence: 10,
      resistance: 10,
      move: 7,
    },
    base_growths: {
      hp: 30,
      strength: 50,
      magic: 5,
      skill: 30,
      speed: 50,
      luck: 35,
      defence: 25,
      resistance: 45,
    },
    personal_skill: getSkill("Bloodthirst"),
    equipped_skills: [
      getSkill("Elbow Room"),
      getSkill("Shelter"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Elbow Room"), getSkill("Shelter")],
    base_class_set: {
      starting_class: getClass("Cavalier"),
      starting_class_tree: getClass("Cavalier"),
      heart_seal_classes: [getClass("Dark Mage")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 12",
    weapon_ranks: {
      WeaponRankSwordKatana: "D",
      WeaponRankLanceNaginata: "C",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 1,
      magic: 0,
      skill: -1,
      speed: 1,
      luck: 0,
      defence: -2,
      resistance: 2,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    personal_pair_up_bonuses_S: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_B: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
  },
  {
    name: "Benny",
    gender: "M",
    title: "Gentle Giant",
    royalty_status: false,
    class: getClass("Knight"),
    baseInternalLevel: 0,
    level: 15,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 15, getClass("Knight")]],
    starting_weapons: ["Steel Lance"],
    stats: {
      hp: 31,
      strength: 15,
      magic: 0,
      skill: 15,
      speed: 6,
      luck: 12,
      defence: 19,
      resistance: 10,
      move: 4,
    },
    base_growths: {
      hp: 50,
      strength: 40,
      magic: 0,
      skill: 50,
      speed: 10,
      luck: 35,
      defence: 55,
      resistance: 45,
    },
    personal_skill: getSkill("Fierce Mien"),
    equipped_skills: [
      getSkill("Defence +2"),
      getSkill("Natural Cover"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Defence +2"), getSkill("Natural Cover")],
    base_class_set: {
      starting_class: getClass("Knight"),
      starting_class_tree: getClass("Knight"),
      heart_seal_classes: [getClass("Fighter")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 13",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "C",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: -3,
      luck: 0,
      defence: 3,
      resistance: 1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 1,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 1,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 5,
    },
    support_bonus_B: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
  },
  {
    name: "Charlotte",
    gender: "F",
    title: "Wily Warrior",
    royalty_status: false,
    class: getClass("Fighter"),
    baseInternalLevel: 0,
    level: 10,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 10, getClass("Fighter")]],
    starting_weapons: ["Steel Axe"],
    stats: {
      hp: 28,
      strength: 15,
      magic: 0,
      skill: 10,
      speed: 13,
      luck: 9,
      defence: 8,
      resistance: 2,
      move: 5,
    },
    base_growths: {
      hp: 65,
      strength: 55,
      magic: 0,
      skill: 35,
      speed: 50,
      luck: 45,
      defence: 20,
      resistance: 5,
    },
    personal_skill: getSkill("Unmask"),
    equipped_skills: [
      getSkill("HP +5"),
      getSkill("Gamble"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("HP +5"), getSkill("Gamble")],
    base_class_set: {
      starting_class: getClass("Fighter"),
      starting_class_tree: getClass("Fighter"),
      heart_seal_classes: [getClass("Troubadour")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 13",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "C",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 3,
      magic: 0,
      skill: 0,
      speed: 2,
      luck: 0,
      defence: -2,
      resistance: -2,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
  },
  {
    name: "Leo",
    gender: "M",
    title: "Sorcerous Prince",
    royalty_status: true,
    class: getClass("Dark Knight"),
    baseInternalLevel: 18,
    level: 2,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[18, 2, getClass("Dark Knight")]],
    starting_weapons: ["Brynhildr", "Iron Sword"],
    stats: {
      hp: 34,
      strength: 14,
      magic: 20,
      skill: 14,
      speed: 15,
      luck: 15,
      defence: 16,
      resistance: 20,
      move: 8,
    },
    base_growths: {
      hp: 45,
      strength: 25,
      magic: 55,
      skill: 35,
      speed: 45,
      luck: 45,
      defence: 30,
      resistance: 45,
    },
    personal_skill: getSkill("Pragmatic"),
    equipped_skills: [
      getSkill("Heartseeker"),
      getSkill("Malefic Aura"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Heartseeker"), getSkill("Malefic Aura")],
    base_class_set: {
      starting_class: getClass("Dark Knight"),
      starting_class_tree: getClass("Dark Mage"),
      heart_seal_classes: [getClass("Troubadour")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 14",
    weapon_ranks: {
      WeaponRankSwordKatana: "D",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "C",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: -2,
      magic: 2,
      skill: 0,
      speed: -2,
      luck: 0,
      defence: 0,
      resistance: 2,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 1,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 1,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 1,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 0,
      magic: 1,
      skill: 0,
      speed: 0,
      luck: 1,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 6,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
  },
  {
    name: "Xander",
    gender: "M",
    title: "Paragon Knight",
    royalty_status: true,
    class: getClass("Paladin"),
    baseInternalLevel: 20,
    level: 4,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[20, 4, getClass("Paladin")]],
    starting_weapons: ["Siegfried"],
    stats: {
      hp: 38,
      strength: 23,
      magic: 4,
      skill: 18,
      speed: 15,
      luck: 20,
      defence: 23,
      resistance: 11,
      move: 8,
    },
    base_growths: {
      hp: 45,
      strength: 50,
      magic: 5,
      skill: 40,
      speed: 35,
      luck: 60,
      defence: 40,
      resistance: 15,
    },
    personal_skill: getSkill("Chivalry"),
    equipped_skills: [
      getSkill("Elbow Room"),
      getSkill("Shelter"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Elbow Room"), getSkill("Shelter")],
    base_class_set: {
      starting_class: getClass("Paladin"),
      starting_class_tree: getClass("Cavalier"),
      heart_seal_classes: [getClass("Wyvern Rider")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 16",
    weapon_ranks: {
      WeaponRankSwordKatana: "B",
      WeaponRankLanceNaginata: "D",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 2,
      magic: -1,
      skill: -1,
      speed: -1,
      luck: 2,
      defence: 1,
      resistance: -2,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 1,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 1,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 1,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 10,
      Hit: 0,
      Avoid: 0,
    },
  },
  {
    name: "Keaton",
    gender: "M",
    title: "Lupine Collector",
    royalty_status: false,
    class: getClass("Wolfskin"),
    baseInternalLevel: 0,
    level: 15,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[0, 15, getClass("Wolfskin")]],
    starting_weapons: ["Beastone", "Beastrune"],
    stats: {
      hp: 35,
      strength: 19,
      magic: 0,
      skill: 10,
      speed: 13,
      luck: 9,
      defence: 16,
      resistance: 7,
      move: 5,
    },
    base_growths: {
      hp: 60,
      strength: 60,
      magic: 0,
      skill: 20,
      speed: 35,
      luck: 30,
      defence: 50,
      resistance: 25,
    },
    personal_skill: getSkill("Collector"),
    equipped_skills: [
      getSkill("Odd Shaped"),
      getSkill("Beastbane"),
      getSkill("N/A"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [getSkill("Odd Shaped"), getSkill("Beastbane")],
    base_class_set: {
      starting_class: getClass("Wolfskin"),
      starting_class_tree: getClass("Wolfskin"),
      heart_seal_classes: [getClass("Fighter")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability: "Chapter 14",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "E",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "E",
      WeaponRankStone: "C",
    },
    maxStatModifiers: {
      strength: 3,
      magic: 0,
      skill: -2,
      speed: -1,
      luck: 0,
      defence: 2,
      resistance: -1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 1,
      resistance: 0,
    },
    personal_pair_up_bonuses_S: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 1,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 0,
      CritAvoid: 5,
      Hit: 5,
      Avoid: 0,
    },
  },
  {
    name: "Flora",
    gender: "F",
    title: "Cold as Ice",
    royalty_status: false,
    class: getClass("Maid"),
    baseInternalLevel: 20,
    level: 5,
    eternalSealCount: 0,
    maxLevelModifier: 0,
    class_line: [[20, 5, getClass("Maid")]],
    starting_weapons: [],
    stats: {
      hp: 29,
      strength: 18,
      magic: 16,
      skill: 25,
      speed: 15,
      luck: 11,
      defence: 14,
      resistance: 23,
      move: 6,
    },
    base_growths: {
      hp: 35,
      strength: 40,
      magic: 20,
      skill: 45,
      speed: 30,
      luck: 35,
      defence: 30,
      resistance: 30,
    },
    personal_skill: getSkill("Icy Blood"),
    equipped_skills: [
      getSkill("Resistance +2"),
      getSkill("Demoiselle"),
      getSkill("Live to Serve"),
      getSkill("N/A"),
      getSkill("N/A"),
    ],
    learned_skills: [
      getSkill("Resistance +2"),
      getSkill("Demoiselle"),
      getSkill("Live to Serve"),
    ],
    base_class_set: {
      starting_class: getClass("Maid"),
      starting_class_tree: getClass("Troubadour"),
      heart_seal_classes: [getClass("Dark Mage"), getClass("Mercenary")],
      friendship_seal_partners: [],
      partner_seal_partners: [],
      selected_friendship_seal_partner: null,
      selected_partner_seal_partner: null,
      friendship_seal_base_class: null,
      partner_seal_base_class: null,
    },
    RouteAvailability:
      "Chapter 19, After upgrading the Launcher or Fire Orb to level 3",
    weapon_ranks: {
      WeaponRankSwordKatana: "E",
      WeaponRankLanceNaginata: "E",
      WeaponRankAxeClub: "E",
      WeaponRankTomeScroll: "E",
      WeaponRankKnifeShuriken: "C",
      WeaponRankBowYumi: "E",
      WeaponRankStaffRod: "B",
      WeaponRankStone: "E",
    },
    maxStatModifiers: {
      strength: 1,
      magic: -1,
      skill: 2,
      speed: 0,
      luck: -1,
      defence: 1,
      resistance: -1,
    },
    personal_pair_up_bonuses_base: {
      dodge: 5,
    },
    personal_pair_up_bonuses_C: {
      strength: 0,
      magic: 0,
      skill: 1,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 0,
    },
    personal_pair_up_bonuses_B: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 1,
      resistance: 0,
    },
    personal_pair_up_bonuses_A: {
      strength: 0,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 0,
      defence: 0,
      resistance: 1,
    },
    personal_pair_up_bonuses_S: {
      strength: 1,
      magic: 0,
      skill: 0,
      speed: 0,
      luck: 1,
      defence: 0,
      resistance: 0,
    },
    support_bonus_base: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 10,
      Avoid: 0,
    },
    support_bonus_C: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_B: {
      Crit: 0,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
    support_bonus_A: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 0,
      Avoid: 0,
    },
    support_bonus_S: {
      Crit: 3,
      CritAvoid: 0,
      Hit: 5,
      Avoid: 0,
    },
  },
];

//const allUnitNames = ["Corrin (M)", "Jakob", "Kaze", "Silas", "Arthur", "Odin", "Niles", "Laslow", "Benny", "Leo", "Xander", "Keaton", "Corrin (F)", "Felicia", "Azura", "Mozu", "Elise", "Effie", "Charlotte", "Camilla", "Selena", "Beruka", "Peri", "Nyx", "Shura", "Gunter", "Izana", "Flora"]
const allStandardMalesNames = [
  "Corrin (M)",
  "Jakob",
  "Kaze",
  "Silas",
  "Arthur",
  "Odin",
  "Niles",
  "Laslow",
  "Benny",
  "Leo",
  "Xander",
  "Keaton",
];
const allStandardFemalesNames = [
  "Corrin (F)",
  "Felicia",
  "Azura",
  "Mozu",
  "Elise",
  "Effie",
  "Charlotte",
  "Camilla",
  "Selena",
  "Beruka",
  "Peri",
  "Nyx",
];

// Friendship seal partners (same-gender friendships)
const friendshipPairs: { [key: string]: string[] } = {
  "Corrin (M)": [
    "Jakob",
    "Kaze",
    "Silas",
    "Arthur",
    "Odin",
    "Niles",
    "Laslow",
    "Benny",
    "Leo",
    "Xander",
    "Keaton",
    "Izana",
    "Gunter",
    "Shura",
  ],
  Jakob: ["Gunter", "Silas"],
  Kaze: ["Silas", "Xander"],
  Silas: ["Jakob", "Kaze"],
  Arthur: ["Benny", "Keaton", "Niles"],
  Odin: ["Laslow", "Niles", "Leo"],
  Niles: ["Odin", "Leo", "Arthur"],
  Laslow: ["Odin", "Xander", "Keaton"],
  Benny: ["Arthur", "Keaton"],
  Leo: ["Niles", "Xander", "Odin"],
  Xander: ["Laslow", "Leo", "Kaze"],
  Keaton: ["Arthur", "Benny", "Laslow"],
  Shura: [],
  Gunter: ["Jakob"],
  Izana: [],
  "Corrin (F)": [
    "Felicia",
    "Azura",
    "Mozu",
    "Elise",
    "Effie",
    "Charlotte",
    "Camilla",
    "Selena",
    "Beruka",
    "Peri",
    "Nyx",
    "Flora",
  ],
  Felicia: ["Peri", "Flora"],
  Azura: ["Elise"],
  Mozu: ["Effie", "Nyx"],
  Elise: ["Effie", "Camilla", "Azura"],
  Effie: ["Mozu", "Elise", "Nyx"],
  Charlotte: ["Beruka", "Peri", "Nyx"],
  Camilla: ["Selena", "Elise", "Beruka"],
  Selena: ["Beruka", "Peri", "Camilla"],
  Beruka: ["Charlotte", "Selena", "Camilla"],
  Peri: ["Charlotte", "Selena", "Felicia"],
  Nyx: ["Mozu", "Effie", "Charlotte"],
  Flora: ["Felicia"],
};

// Partner seal partners (opposite-gender S-rank supports)
const partnerPairs: { [key: string]: string[] } = {
  "Corrin (M)": [...allStandardFemalesNames, "Niles"],
  Jakob: [...allStandardFemalesNames],
  Kaze: [...allStandardFemalesNames],
  Silas: [...allStandardFemalesNames],
  Arthur: [...allStandardFemalesNames],
  Odin: [...allStandardFemalesNames],
  Niles: [...allStandardFemalesNames],
  Laslow: [...allStandardFemalesNames],
  Benny: [...allStandardFemalesNames],
  Leo: [
    "Corrin (F)",
    "Felicia",
    "Azura",
    "Mozu",
    "Effie",
    "Charlotte",
    "Selena",
    "Beruka",
    "Peri",
    "Nyx",
  ],
  Xander: [
    "Corrin (F)",
    "Felicia",
    "Azura",
    "Mozu",
    "Effie",
    "Charlotte",
    "Selena",
    "Beruka",
    "Peri",
    "Nyx",
  ],
  Keaton: [...allStandardFemalesNames],
  Shura: ["Corrin (F)"],
  Gunter: ["Corrin (F)"],
  Izana: ["Corrin (F)"],
  "Corrin (F)": [...allStandardMalesNames],
  Felicia: [...allStandardMalesNames],
  Azura: [...allStandardMalesNames],
  Mozu: [...allStandardMalesNames],
  Elise: [
    "Corrin (M)",
    "Jakob",
    "Kaze",
    "Silas",
    "Arthur",
    "Odin",
    "Niles",
    "Laslow",
    "Benny",
    "Keaton",
  ],
  Effie: [...allStandardMalesNames],
  Charlotte: [...allStandardMalesNames],
  Camilla: [
    "Corrin (M)",
    "Jakob",
    "Kaze",
    "Silas",
    "Arthur",
    "Odin",
    "Niles",
    "Laslow",
    "Benny",
    "Keaton",
  ],
  Selena: [...allStandardMalesNames],
  Beruka: [...allStandardMalesNames],
  Peri: [...allStandardMalesNames],
  Nyx: [...allStandardMalesNames],
  Flora: ["Corrin (M)"],
};

// Helper function to find a character by name
export const findCharacter = (name: string): Character => {
  const character = defaultCharactersConquest.find(
    (char) => char.name === name,
  );
  if (!character) throw new Error(`Character ${name} not found`);
  return character;
};

// Populate the friendship_seal_partners and partner_seal_partners
defaultCharactersConquest.forEach((character) => {
  // Populate friendship_seal_partners (same-gender friendships)
  const friends = friendshipPairs[character.name] || [];
  character.base_class_set.friendship_seal_partners = friends.map(
    (friendName) => findCharacter(friendName),
  );

  // Populate partner_seal_partners (opposite-gender S-rank supports)
  const partners = partnerPairs[character.name] || [];
  character.base_class_set.partner_seal_partners = partners.map((partnerName) =>
    findCharacter(partnerName),
  );
});

// console.log(defaultCharactersConquest[0]);
//unit template
// {
//   name: "",
//   gender: "",
//   title: "",
//   royalty_status: ,
//   class: getClass(""),
//   baseInternalLevel: ,
//   level: ,
//   starting_weapons: [],
//   stats: {
//     hp: 0,
//     strength: 0,
//     magic: 0,
//     skill: 0,
//     speed: 0,
//     luck: 0,
//     defence: 0,
//     resistance: 0,
//     move: 0,
//   },
//   base_growths: {
//     hp: 0,
//     strength: 0,
//     magic: 0,
//     skill: 0,
//     speed: 0,
//     luck: 0,
//     defence: 0,
//     resistance: 0,
//   },
//   personal_skill: getSkill(""),
//   equipped_skills: [
//     getSkill("N/A"),
//     getSkill("N/A"),
//     getSkill("N/A"),
//     getSkill("N/A"),
//     getSkill("N/A"),
//   ],
//   base_class_set: {
//     starting_class: getClass(""),
//     starting_class_tree: getClass(""),
//     heart_seal_classes: [getClass("")],
//     friendship_seal_partners: [],
//     partner_seal_partners: [],
//     friendship_seal_base_class: null,
//     partner_seal_base_class: null,
//   },
//   RouteAvailability: "Chapter ",
//   weapon_ranks: {
//     WeaponRankSwordKatana: "E",
//     WeaponRankLanceNaginata: "E",
//     WeaponRankAxeClub: "E",
//     WeaponRankTomeScroll: "E",
//     WeaponRankKnifeShuriken: "E",
//     WeaponRankBowYumi: "E",
//     WeaponRankStaffRod: "E",
//     WeaponRankStone: "E",
//   },
//   maxStatModifiers: {
//     strength: 0,
//     magic: 0,
//     skill: 0,
//     speed: 0,
//     luck: 0,
//     defence: 0,
//     resistance: 0,
//   },
//   personal_pair_up_bonuses_base: {
//     dodge: 5,
//   },
//   personal_pair_up_bonuses_C: {
//     strength: 0,
//     magic: 0,
//     skill: 0,
//     speed: 0,
//     luck: 0,
//     defence: 0,
//     resistance: 0,
//   },
//   personal_pair_up_bonuses_B: {
//     strength: 0,
//     magic: 0,
//     skill: 0,
//     speed: 0,
//     luck: 0,
//     defence: 0,
//     resistance: 0,
//   },
//   personal_pair_up_bonuses_A: {
//     strength: 0,
//     magic: 0,
//     skill: 0,
//     speed: 0,
//     luck: 0,
//     defence: 0,
//     resistance: 0,
//   },
//   personal_pair_up_bonuses_S: {
//     strength: 0,
//     magic: 0,
//     skill: 0,
//     speed: 0,
//     luck: 0,
//     defence: 0,
//     resistance: 0,
//   },
//   support_bonus_base: {
//     Crit: 0,
//     CritAvoid: 0,
//     Hit: 10,
//     Avoid: 0,
//   },
//   support_bonus_C: {
//     Crit: 0,
//     CritAvoid: 0,
//     Hit: 0,
//     Avoid: 0,
//   },
//   support_bonus_B: {
//     Crit: 0,
//     CritAvoid: 0,
//     Hit: 0,
//     Avoid: 0,
//   },
//   support_bonus_A: {
//     Crit: 0,
//     CritAvoid: 0,
//     Hit: 0,
//     Avoid: 0,
//   },
//   support_bonus_S: {
//     Crit: 0,
//     CritAvoid: 0,
//     Hit: 0,
//     Avoid: 0,
//   },
// },
